"""
Search tags for emojis — includes German terms, synonyms, and common aliases.
Maps emoji character to a list of additional search terms.
"""

SEARCH_TAGS = {
    # Smileys
    "😀": ["grinsen", "lachen", "happy", "smile", "grin", "freude"],
    "😃": ["grinsen", "lachen", "happy", "smile", "freude", "fröhlich"],
    "😄": ["grinsen", "lachen", "happy", "smile", "freude", "fröhlich"],
    "😁": ["grinsen", "lachen", "strahlen", "beam", "happy"],
    "😆": ["lachen", "haha", "xD", "laugh", "lustig"],
    "😅": ["schwitzen", "sweat", "nervös", "nervous", "lachen"],
    "🤣": ["rofl", "lol", "totlachen", "laugh", "lustig", "witzig"],
    "😂": ["lol", "lachen", "tränen", "tears", "laugh", "lustig", "witzig", "haha"],
    "🙂": ["lächeln", "smile", "leicht", "slight"],
    "🙃": ["verkehrt", "upside", "sarkasmus", "ironie", "sarcasm"],
    "🫠": ["schmelzen", "zerfließen", "melting", "overwhelmed", "überfordert", "heiß"],
    "😉": ["zwinkern", "wink", "augenzwinkern"],
    "😊": ["lächeln", "smile", "verlegen", "shy", "blush", "süß"],
    "😇": ["engel", "angel", "heilig", "holy", "brav"],
    "🥰": ["verliebt", "love", "herzen", "hearts", "liebe", "schwärmen"],
    "😍": ["verliebt", "love", "herzaugen", "heart eyes", "liebe"],
    "🤩": ["star", "stern", "begeistert", "wow", "amazing", "toll"],
    "😘": ["kuss", "kiss", "bussi", "küsschen", "herz"],
    "😗": ["kuss", "kiss", "bussi"],
    "😚": ["kuss", "kiss", "bussi"],
    "😙": ["kuss", "kiss", "bussi"],
    "🥲": ["traurig", "lächeln", "träne", "sad", "smile", "tear"],
    "😋": ["lecker", "yummy", "essen", "food", "delicious", "mmh"],
    "😛": ["zunge", "tongue", "frech", "raus"],
    "😜": ["zunge", "zwinkern", "frech", "wink", "tongue", "crazy"],
    "🤪": ["verrückt", "crazy", "wild", "zany", "wahnsinn"],
    "😝": ["zunge", "tongue", "bäh", "frech"],
    "🤑": ["geld", "money", "reich", "dollar", "cash"],
    "🤗": ["umarmen", "hug", "umarmung", "knuddeln"],
    "🤭": ["kichern", "giggle", "oops", "ups", "huch"],
    "🫢": ["überrascht", "shocked", "oops", "oh nein", "augen auf", "mund zu"],
    "🫣": ["gucken", "peek", "spähen", "neugierig", "curious", "schauen"],
    "🤫": ["pst", "leise", "shh", "quiet", "still", "geheim", "secret"],
    "🤔": ["denken", "think", "hmm", "überlegen", "nachdenken", "grübeln"],
    "🫡": ["salut", "salute", "jawohl", "respekt"],
    "🤐": ["mund zu", "zip", "still", "quiet", "reißverschluss"],
    "🤨": ["skeptisch", "suspicious", "hmm", "zweifel", "doubt"],
    "😐": ["neutral", "meh", "gleichgültig"],
    "😑": ["genervt", "annoyed", "ausdruckslos", "meh"],
    "😶": ["still", "silent", "speechless", "sprachlos", "kein kommentar"],
    "😶‍🌫️": ["nebel", "fog", "sprachlos", "speechless", "verloren", "wolke", "cloud"],
    "😏": ["grinsen", "smirk", "frech", "schlau", "hehe"],
    "😒": ["genervt", "unamused", "gelangweilt", "bored", "meh"],
    "🙄": ["augenrollen", "eye roll", "genervt", "nervig", "bitte"],
    "😬": ["grimasse", "awkward", "peinlich", "oops", "yikes"],
    "🤥": ["lügen", "lie", "pinocchio", "lügner"],
    "😌": ["erleichtert", "relieved", "entspannt", "relaxed", "frieden"],
    "😔": ["nachdenklich", "traurig", "sad", "down"],
    "😪": ["müde", "sleepy", "tired", "schläfrig"],
    "🤤": ["sabbern", "drool", "lecker", "hunger"],
    "😴": ["schlafen", "sleep", "müde", "tired", "zzz", "pennen"],
    "😷": ["maske", "mask", "krank", "sick", "corona", "covid"],
    "🤒": ["krank", "sick", "fieber", "fever", "thermometer"],
    "🤕": ["verletzt", "hurt", "kopf", "bandage", "aua", "autsch"],
    "🤢": ["übel", "nausea", "kotzen", "sick", "grün"],
    "🤮": ["kotzen", "vomit", "übergeben", "sick", "bah"],
    "🥵": ["heiß", "hot", "schwitzen", "hitze", "warm"],
    "🥶": ["kalt", "cold", "frieren", "frost", "eisig"],
    "🥴": ["betrunken", "drunk", "benommen", "dizzy", "woozy"],
    "😵": ["schwindel", "dizzy", "ko", "ohnmacht"],
    "🤯": ["explodieren", "mind blown", "wow", "krass", "wahnsinn"],
    "🤠": ["cowboy", "western", "yeehaw"],
    "🥳": ["party", "feier", "geburtstag", "birthday", "feiern"],
    "🥸": ["verkleidet", "disguise", "inkognito", "tarnung"],
    "😎": ["cool", "sonnenbrille", "sunglasses", "lässig"],
    "🤓": ["nerd", "streber", "brille", "schlau", "geek"],
    "🧐": ["monokel", "schick", "fancy", "prüfen", "inspect"],
    "😕": ["verwirrt", "confused", "unsicher", "hä"],
    "😟": ["besorgt", "worried", "sorge"],
    "🙁": ["traurig", "sad", "frown", "enttäuscht"],
    "😮": ["oh", "überrascht", "surprised", "wow"],
    "😯": ["überrascht", "surprised", "oh"],
    "😲": ["erstaunt", "astonished", "schock", "shocked", "wow"],
    "😳": ["peinlich", "embarrassed", "rot", "blush", "flush"],
    "🥺": ["bitte", "please", "flehen", "süß", "cute", "puppy"],
    "🥹": ["rührung", "tears", "emotional", "gerührt"],
    "😨": ["angst", "fear", "scared", "erschrocken"],
    "😰": ["angst", "schwitzen", "anxious", "nervous", "stress"],
    "😥": ["traurig", "erleichtert", "sad"],
    "😢": ["weinen", "cry", "traurig", "sad", "träne"],
    "😭": ["heulen", "weinen", "cry", "traurig", "sad", "schluchzen"],
    "😱": ["schreien", "scream", "horror", "schock", "angst", "panik"],
    "😖": ["frustration", "verzweifelt", "ugh"],
    "😣": ["anstrengung", "persevere", "durchhalten"],
    "😞": ["enttäuscht", "disappointed", "traurig", "sad"],
    "😓": ["schwitzen", "stress", "erschöpft"],
    "😩": ["erschöpft", "weary", "tired", "müde", "fertig"],
    "😫": ["müde", "tired", "erschöpft", "fertig"],
    "🥱": ["gähnen", "yawn", "müde", "langweilig", "boring"],
    "😤": ["wütend", "angry", "dampf", "steam", "sauer"],
    "😡": ["wütend", "angry", "sauer", "zorn", "rage", "mad"],
    "😠": ["wütend", "angry", "sauer", "böse", "mad"],
    "🤬": ["fluchen", "swear", "schimpfen", "wütend", "angry"],
    "😈": ["teufel", "devil", "böse", "evil", "frech"],
    "👿": ["teufel", "devil", "böse", "evil", "wütend"],
    "💀": ["tot", "dead", "skull", "schädel", "totenkopf", "rip"],
    "☠️": ["tot", "dead", "gift", "poison", "gefahr", "danger"],
    "💩": ["kacke", "poop", "shit", "mist", "scheiße"],
    "🤡": ["clown", "lustig", "witzig", "zirkus"],
    "👹": ["dämon", "demon", "monster", "ungeheuer"],
    "👺": ["kobold", "goblin", "maske"],
    "👻": ["geist", "ghost", "spuk", "halloween", "boo"],
    "👽": ["alien", "außerirdisch", "ufo"],
    "👾": ["alien", "monster", "videospiel", "game", "pixel"],
    "🤖": ["roboter", "robot", "maschine", "ki", "ai"],
    "😺": ["katze", "cat", "lachen", "grinsen"],
    "😸": ["katze", "cat", "lachen"],
    "😹": ["katze", "cat", "lachen", "freude"],
    "😻": ["katze", "cat", "verliebt", "herz"],
    "😼": ["katze", "cat", "grinsen"],
    "😽": ["katze", "cat", "kuss"],
    "🙀": ["katze", "cat", "schock", "oh nein"],
    "😿": ["katze", "cat", "traurig", "weinen"],
    "😾": ["katze", "cat", "wütend", "sauer"],
    "🫶": ["herzhände", "heart hands", "liebe", "love", "danke"],
    "❤️": ["herz", "heart", "liebe", "love", "rot", "red"],
    "🧡": ["herz", "heart", "orange", "liebe"],
    "💛": ["herz", "heart", "gelb", "yellow", "liebe"],
    "💚": ["herz", "heart", "grün", "green", "liebe"],
    "💙": ["herz", "heart", "blau", "blue", "liebe"],
    "💜": ["herz", "heart", "lila", "purple", "liebe"],
    "🖤": ["herz", "heart", "schwarz", "black", "trauer"],
    "🤍": ["herz", "heart", "weiß", "white"],
    "🤎": ["herz", "heart", "braun", "brown"],
    "💔": ["herz", "gebrochen", "broken", "traurig", "herzschmerz", "liebeskummer"],
    "❤️‍🔥": ["herz", "feuer", "fire", "leidenschaft", "passion"],
    "❤️‍🩹": ["herz", "heilung", "healing", "pflaster"],
    "💕": ["herzen", "hearts", "liebe", "love"],
    "💞": ["herzen", "hearts", "liebe", "love"],
    "💓": ["herz", "heart", "schlagen", "beat"],
    "💗": ["herz", "heart", "wachsen", "growing"],
    "💖": ["herz", "heart", "funkeln", "sparkle"],
    "💘": ["herz", "heart", "amor", "pfeil", "arrow", "verliebt"],
    "💝": ["herz", "heart", "geschenk", "gift", "schleife"],
    "💟": ["herz", "heart", "dekoration"],
    "🩷": ["herz", "heart", "pink", "rosa"],
    "🩵": ["herz", "heart", "hellblau", "light blue"],
    "🩶": ["herz", "heart", "grau", "grey"],
    "💯": ["hundert", "hundred", "perfekt", "perfect", "100", "top"],
    "💢": ["wut", "anger", "ärger"],
    "💥": ["explosion", "boom", "crash", "knall", "bumm"],
    "💫": ["schwindel", "stern", "star", "dizzy"],
    "💦": ["schweiß", "tropfen", "sweat", "wasser", "water"],
    "💨": ["wind", "schnell", "fast", "pups", "fart", "weg"],
    "💬": ["sprechblase", "speech", "chat", "nachricht", "message"],
    "💭": ["denken", "thought", "gedanke"],
    "💤": ["schlafen", "sleep", "müde", "zzz"],
    "🫥": ["gepunktetes gesicht", "dotted line face", "unsichtbar", "invisible", "ausgegrenzt", "transparent"],
    "🫨": ["zittern", "shaking face", "erschüttert", "schockiert", "shocked", "beben", "vibrate"],
    "🫤": ["diagonal mund", "face with diagonal mouth", "unentschlossen", "meh", "unzufrieden", "so lala"],
    "😦": ["schockiert", "frowning open mouth", "mund offen", "überrascht", "dismay", "entsetzt"],
    "😧": ["gequält", "anguished face", "schmerz", "angst", "distress", "erschrocken"],
    "🕳️": ["loch", "hole", "grube", "pit", "schwarz", "verschwinden"],
    "🗯️": ["wut", "anger bubble", "sprechblase", "gedankenblase", "schreien", "zorn", "comic"],
    "🗨️": ["sprechblase", "left speech bubble", "dialog", "chat", "comic", "sprechen"],

    # People & Body
    "👋": ["winken", "wave", "hallo", "hello", "hi", "tschüss", "bye"],
    "🤚": ["hand", "stop", "halt"],
    "🖐️": ["hand", "finger", "fünf", "five", "high five"],
    "✋": ["hand", "stop", "halt", "high five"],
    "🖖": ["vulkanier", "spock", "star trek", "live long"],
    "👌": ["ok", "okay", "gut", "good", "perfekt", "perfect", "nice"],
    "🤌": ["italian", "italienisch", "was willst du", "chef kiss"],
    "🤏": ["wenig", "little", "klein", "small", "bisschen", "tiny"],
    "✌️": ["victory", "sieg", "frieden", "peace", "zwei", "two"],
    "🤞": ["daumen drücken", "fingers crossed", "glück", "luck", "hoffen"],
    "🤟": ["liebe", "love", "rock"],
    "🤘": ["rock", "metal", "party", "teufel"],
    "🤙": ["anrufen", "call", "hang loose", "shaka", "ruf an"],
    "👈": ["links", "left", "zeigen", "point"],
    "👉": ["rechts", "right", "zeigen", "point"],
    "👆": ["oben", "up", "zeigen", "point"],
    "🖕": ["mittelfinger", "fuck", "fick dich"],
    "👇": ["unten", "down", "zeigen", "point"],
    "☝️": ["eins", "one", "oben", "achtung", "attention"],
    "🫵": ["du", "you", "zeigen", "point"],
    "👍": ["daumen hoch", "thumbs up", "gut", "good", "ja", "yes", "like", "top", "ok"],
    "👎": ["daumen runter", "thumbs down", "schlecht", "bad", "nein", "no", "dislike"],
    "✊": ["faust", "fist", "kraft", "power", "stark", "strong"],
    "👊": ["faust", "fist", "schlag", "punch", "bro"],
    "🤛": ["faust", "fist", "links"],
    "🤜": ["faust", "fist", "rechts"],
    "👏": ["klatschen", "clap", "applaus", "bravo", "applause"],
    "🙌": ["hände hoch", "celebration", "feier", "jubel", "hooray", "yay"],
    "👐": ["hände", "hands", "offen", "open"],
    "🤲": ["hände", "beten", "bitte", "geben"],
    "🤝": ["handschlag", "handshake", "deal", "abmachung", "vereinbarung"],
    "🙏": ["beten", "pray", "bitte", "please", "danke", "thanks", "namaste"],
    "✍️": ["schreiben", "write", "unterschrift"],
    "💅": ["nagellack", "nail", "schick", "fancy", "slay"],
    "🤳": ["selfie", "foto", "photo"],
    "💪": ["stark", "strong", "bizeps", "muscle", "kraft", "power", "gym", "sport"],
    "👀": ["augen", "eyes", "gucken", "schauen", "look", "see"],
    "👁️": ["auge", "eye", "sehen", "see"],
    "👅": ["zunge", "tongue", "lecken"],
    "👄": ["mund", "mouth", "lippen", "lips", "kuss"],
    "🫦": ["beißen", "bite", "lippe", "lip", "nervös"],
    "👶": ["baby", "kind", "child", "säugling"],
    "👦": ["junge", "boy", "kind"],
    "👧": ["mädchen", "girl", "kind"],
    "👨": ["mann", "man", "herr", "typ", "kerl", "guy"],
    "👩": ["frau", "woman", "dame", "lady"],
    "👴": ["opa", "grandpa", "alter mann", "old man", "rentner"],
    "👵": ["oma", "grandma", "alte frau", "old woman", "rentnerin"],
    "🤦": ["facepalm", "kopf schlagen", "ach nee", "oh mann", "doh"],
    "🤷": ["keine ahnung", "shrug", "weiß nicht", "egal", "idk", "dunno"],
    "👮": ["polizei", "police", "cop", "polizist"],
    "🕵️": ["detektiv", "detective", "spion", "spy", "ermittler"],
    "💂": ["wache", "guard", "soldat"],
    "🥷": ["ninja", "kämpfer", "shinobi"],
    "👷": ["bauarbeiter", "construction", "baustelle", "helm"],
    "🤴": ["prinz", "prince", "könig"],
    "👸": ["prinzessin", "princess", "königin"],
    "🎅": ["weihnachtsmann", "santa", "weihnachten", "christmas", "nikolaus"],
    "🤶": ["weihnachtsfrau", "mrs claus", "weihnachten"],
    "🦸": ["superheld", "superhero", "held", "hero"],
    "🦹": ["superschurke", "villain", "böse"],
    "🧙": ["zauberer", "mage", "wizard", "magie", "magic"],
    "🧚": ["fee", "fairy", "elfe"],
    "🧛": ["vampir", "vampire", "dracula"],
    "🧜": ["meerjungfrau", "mermaid", "merman"],
    "🧝": ["elfe", "elf"],
    "🧟": ["zombie", "untot", "undead"],
    "💃": ["tanzen", "dance", "frau", "salsa", "tanz"],
    "🕺": ["tanzen", "dance", "mann", "disco", "tanz"],
    "🏃": ["rennen", "run", "joggen", "laufen", "sprint"],
    "🚶": ["gehen", "walk", "spazieren", "laufen"],
    "🧍": ["stehen", "stand", "person"],
    "🧎": ["knien", "kneel"],
    "💏": ["kuss", "kiss", "pärchen", "couple"],
    "💑": ["pärchen", "couple", "liebe", "love"],
    "👪": ["familie", "family", "eltern", "kinder"],
    "🫂": ["umarmung", "hug", "umarmen", "trost"],
    "👣": ["fußabdruck", "footprint", "füße", "feet", "schritte"],
    "🫱": ["hand nach rechts", "rightwards hand", "handreichen", "geben", "reach"],
    "🫲": ["hand nach links", "leftwards hand", "handreichen", "geben", "reach"],
    "🫳": ["handfläche nach unten", "palm down hand", "ablehnen", "no", "stop", "nach unten"],
    "🫴": ["handfläche nach oben", "palm up hand", "anbieten", "offer", "geben"],
    "🫷": ["schieben", "leftwards pushing hand", "stopp", "push", "drücken", "zurück"],
    "🫸": ["schieben", "rightwards pushing hand", "stopp", "push", "drücken", "vorwärts"],
    "🫰": ["fingerschnippen", "hand with index finger and thumb crossed", "schnipsen", "snap", "kreuzen"],
    "🦾": ["mechanischer arm", "mechanical arm", "prothese", "prosthesis", "roboter", "cyborg", "stärke"],
    "🦿": ["mechanisches bein", "mechanical leg", "prothese", "prosthesis", "roboter", "cyborg"],
    "🦵": ["bein", "leg", "oberschenkel", "thigh", "körper", "body"],
    "🦶": ["fuß", "foot", "zehen", "toes", "körper"],
    "👂": ["ohr", "ear", "hören", "listen", "hearing"],
    "🦻": ["ohr", "ear with hearing aid", "hörgerät", "schwerhörig", "hearing aid", "gehörlos"],
    "👃": ["nase", "nose", "riechen", "smell", "schnüffeln"],
    "🧠": ["gehirn", "brain", "denken", "think", "intelligent", "klug", "smart"],
    "🫀": ["herz", "anatomical heart", "organ", "anatomie", "anatomy", "herzschlag"],
    "🫁": ["lunge", "lungs", "atmen", "breathe", "organ", "anatomie"],
    "🦷": ["zahn", "tooth", "zähne", "teeth", "zahnarzt", "dentist"],
    "🦴": ["knochen", "bone", "skelett", "skeleton", "hund"],
    "🧒": ["kind", "child", "mädchen", "junge", "jung", "youth"],
    "🧑": ["person", "mensch", "erwachsen", "adult"],
    "👱": ["person blond", "person blond hair", "blond", "blonde", "haare"],
    "🧔": ["bart", "person beard", "bartträger", "bearded", "beard"],
    "🧓": ["ältere person", "older person", "senior", "alt", "old"],
    "🙍": ["unzufrieden", "person frowning", "traurig", "missmutig", "disappointed"],
    "🙎": ["schmollen", "person pouting", "sauer", "schmollend", "pouting"],
    "🙅": ["nein", "person gesturing NO", "ablehnen", "verboten", "no", "stop", "abweisen"],
    "🙆": ["ok", "person gesturing OK", "einverstanden", "okay", "gut"],
    "💁": ["auskunft", "person tipping hand", "info", "information", "hinweis", "bedienung"],
    "🙋": ["melden", "person raising hand", "hand heben", "frage", "question"],
    "🧏": ["gehörlos", "deaf person", "taubstumm", "gebärde", "sign language"],
    "🫅": ["krone", "person with crown", "royalty", "könig", "adel", "noble"],
    "👳": ["turban", "person wearing turban", "sikh", "indisch", "kopfbedeckung"],
    "👲": ["kappe", "person with skullcap", "china", "chinesisch", "kopfbedeckung"],
    "🧕": ["kopftuch", "woman with headscarf", "hijab", "islam", "muslimisch"],
    "🤵": ["smoking", "person in tuxedo", "frack", "tuxedo", "hochzeit", "elegant", "gala"],
    "👰": ["schleier", "person with veil", "braut", "bride", "hochzeit", "wedding"],
    "🤰": ["schwanger", "pregnant woman", "schwangerschaft", "pregnancy", "babybauch"],
    "🫄": ["schwanger", "pregnant person", "schwangerschaft", "pregnancy", "babybauch"],
    "🤱": ["stillen", "breast-feeding", "säugling", "mutter", "mother", "baby"],
    "👼": ["babyengel", "baby angel", "engel", "angel", "cherub", "heilig"],
    "🧞": ["geist", "genie", "djinn", "wunsch", "wish", "lampe", "aladdin", "magie"],
    "🧌": ["troll", "monster", "fabelwesen", "fantasy", "böse"],
    "💆": ["massage", "person getting massage", "entspannen", "relaxen", "spa", "wellness"],
    "💇": ["friseur", "person getting haircut", "haare schneiden", "salon", "haircut"],
    "🕴️": ["schwebend", "person in suit levitating", "anzug", "suit", "levitieren", "fliegen", "geschäft"],
    "👯": ["bunny ears", "people with bunny ears", "hasenohren", "tanzen", "party", "verkleidet"],
    "🧖": ["dampfbad", "person in steamy room", "sauna", "wellness", "spa", "entspannen"],
    "🧗": ["klettern", "person climbing", "bouldern", "klettersteig", "sport"],
    "🤺": ["fechten", "person fencing", "degen", "florett", "fechtkampf", "sport"],
    "🏇": ["pferderennen", "horse racing", "reiten", "rennen", "jockey", "sport"],
    "⛷️": ["skifahrer", "skier", "ski", "winter", "schnee", "abfahrt", "sport"],
    "🏂": ["snowboard", "snowboarder", "winter", "schnee", "sport", "halfpipe"],
    "🏋️": ["gewichtheben", "person lifting weights", "training", "gym", "fitnessstudio", "sport", "hantel"],
    "🤸": ["rad schlagen", "person cartwheeling", "akrobatik", "turnen", "sport", "gymnast"],
    "🤼": ["ringen", "people wrestling", "kampf", "wrestle", "sport", "ringkampf"],
    "🤽": ["wasserball", "person playing water polo", "schwimmen", "sport", "pool"],
    "🤾": ["handball", "person playing handball", "sport", "werfen", "throw"],
    "🤹": ["jonglieren", "person juggling", "zirkus", "circus", "akrobatik", "geschicklichkeit"],
    "🧘": ["yoga", "person in lotus position", "meditation", "entspannen", "lotus", "meditieren"],
    "👫": ["pärchen", "woman and man holding hands", "händchen", "liebe", "couple", "love"],
    "👬": ["männer", "men holding hands", "händchen", "pärchen", "gay", "couple"],
    "👭": ["frauen", "women holding hands", "händchen", "pärchen", "lesbian", "couple"],
    "🗣️": ["sprechen", "speaking head", "reden", "stimme", "voice", "laut"],
    "👤": ["silhouette", "bust in silhouette", "anonym", "profil", "user", "person"],
    "👥": ["silhouetten", "busts in silhouette", "gruppe", "group", "team", "user", "personen"],

    # Animals & Nature
    "🐵": ["affe", "monkey", "ape"],
    "🐒": ["affe", "monkey", "ape"],
    "🦍": ["gorilla", "affe", "ape"],
    "🦧": ["orang utan", "affe", "ape"],
    "🐶": ["hund", "dog", "welpe", "puppy", "wuff", "wau"],
    "🐕": ["hund", "dog"],
    "🐩": ["pudel", "poodle", "hund", "dog"],
    "🐺": ["wolf", "heulen", "howl"],
    "🦊": ["fuchs", "fox", "schlau"],
    "🦝": ["waschbär", "raccoon"],
    "🐱": ["katze", "cat", "mieze", "miau", "kitty"],
    "🐈": ["katze", "cat"],
    "🐈‍⬛": ["katze", "cat", "schwarz", "black"],
    "🦁": ["löwe", "lion", "könig"],
    "🐯": ["tiger"],
    "🐅": ["tiger"],
    "🐆": ["leopard", "gepard", "cheetah"],
    "🐴": ["pferd", "horse", "pony", "ross"],
    "🐎": ["pferd", "horse", "rennen", "race", "reiten"],
    "🦄": ["einhorn", "unicorn", "magisch", "magic"],
    "🦓": ["zebra"],
    "🦌": ["hirsch", "deer", "reh", "bambi"],
    "🐮": ["kuh", "cow", "muh"],
    "🐄": ["kuh", "cow", "milch"],
    "🐷": ["schwein", "pig", "sau", "oink"],
    "🐖": ["schwein", "pig"],
    "🐗": ["wildschwein", "boar"],
    "🐏": ["schaf", "sheep", "widder", "ram"],
    "🐑": ["schaf", "sheep", "lamm", "lamb", "wolle"],
    "🐐": ["ziege", "goat"],
    "🐪": ["kamel", "camel", "wüste", "desert"],
    "🐫": ["kamel", "camel", "wüste"],
    "🦒": ["giraffe"],
    "🐘": ["elefant", "elephant"],
    "🦏": ["nashorn", "rhino"],
    "🦛": ["nilpferd", "hippo", "flusspferd"],
    "🐭": ["maus", "mouse"],
    "🐁": ["maus", "mouse"],
    "🐀": ["ratte", "rat"],
    "🐹": ["hamster"],
    "🐰": ["hase", "rabbit", "kaninchen", "bunny", "ostern", "easter"],
    "🐇": ["hase", "rabbit", "kaninchen"],
    "🐿️": ["eichhörnchen", "chipmunk", "squirrel"],
    "🦔": ["igel", "hedgehog"],
    "🦇": ["fledermaus", "bat", "batman", "halloween"],
    "🐻": ["bär", "bear", "teddy"],
    "🐻‍❄️": ["eisbär", "polar bear", "arktis"],
    "🐨": ["koala"],
    "🐼": ["panda", "bär"],
    "🦥": ["faultier", "sloth", "faul", "lazy"],
    "🦦": ["otter"],
    "🦨": ["stinktier", "skunk"],
    "🦘": ["känguru", "kangaroo"],
    "🐾": ["pfote", "paw", "tatze", "tier", "animal"],
    "🦃": ["truthahn", "turkey", "thanksgiving"],
    "🐔": ["huhn", "chicken", "henne", "hen"],
    "🐓": ["hahn", "rooster"],
    "🐣": ["küken", "chick", "schlüpfen", "hatch"],
    "🐤": ["küken", "chick", "baby"],
    "🐥": ["küken", "chick"],
    "🐦": ["vogel", "bird"],
    "🐧": ["pinguin", "penguin"],
    "🕊️": ["taube", "dove", "frieden", "peace"],
    "🦅": ["adler", "eagle"],
    "🦆": ["ente", "duck", "quak"],
    "🦢": ["schwan", "swan"],
    "🦉": ["eule", "owl", "uhu"],
    "🦩": ["flamingo"],
    "🦚": ["pfau", "peacock"],
    "🦜": ["papagei", "parrot"],
    "🪿": ["gans", "goose"],
    "🐸": ["frosch", "frog", "kröte", "quak"],
    "🐊": ["krokodil", "crocodile", "alligator"],
    "🐢": ["schildkröte", "turtle", "langsam", "slow"],
    "🦎": ["eidechse", "lizard", "gecko"],
    "🐍": ["schlange", "snake"],
    "🐲": ["drache", "dragon"],
    "🐉": ["drache", "dragon"],
    "🦕": ["dinosaurier", "dino", "sauropod"],
    "🦖": ["dinosaurier", "dino", "t-rex", "trex"],
    "🐳": ["wal", "whale", "meer", "sea"],
    "🐋": ["wal", "whale"],
    "🐬": ["delfin", "dolphin"],
    "🦈": ["hai", "shark"],
    "🐙": ["oktopus", "octopus", "krake", "tintenfisch"],
    "🐚": ["muschel", "shell", "strand", "beach"],
    "🐌": ["schnecke", "snail", "langsam", "slow"],
    "🦋": ["schmetterling", "butterfly"],
    "🐛": ["raupe", "bug", "insekt", "wurm"],
    "🐜": ["ameise", "ant", "insekt"],
    "🐝": ["biene", "bee", "honig", "honey", "hummel"],
    "🪲": ["käfer", "beetle", "insekt"],
    "🐞": ["marienkäfer", "ladybug", "glück", "luck"],
    "🕷️": ["spinne", "spider"],
    "🕸️": ["spinnennetz", "spider web", "netz"],
    "🦂": ["skorpion", "scorpion"],
    "🦟": ["mücke", "mosquito", "stich"],
    "🌸": ["kirschblüte", "cherry blossom", "blume", "flower", "japan", "frühling", "spring"],
    "💐": ["blumenstrauß", "bouquet", "blumen", "flowers"],
    "🌷": ["tulpe", "tulip", "blume", "flower", "holland"],
    "🌹": ["rose", "blume", "flower", "liebe", "love", "romantisch"],
    "🥀": ["welk", "wilted", "traurig", "sad", "rose"],
    "🌻": ["sonnenblume", "sunflower", "sommer", "summer"],
    "🌼": ["blüte", "blossom", "blume", "flower"],
    "🌱": ["sprössling", "seedling", "pflanze", "plant", "wachsen", "grow"],
    "🪴": ["topfpflanze", "plant", "pflanze", "zimmerpflanze"],
    "🌲": ["nadelbaum", "evergreen", "tannenbaum", "tanne", "fichte", "wald", "forest"],
    "🌳": ["baum", "tree", "laubbaum", "wald"],
    "🌴": ["palme", "palm", "urlaub", "vacation", "strand", "beach", "tropen"],
    "🌵": ["kaktus", "cactus", "wüste", "desert"],
    "🌾": ["reis", "wheat", "getreide", "feld", "ernte"],
    "🍀": ["kleeblatt", "clover", "glück", "luck", "irland"],
    "🍁": ["ahornblatt", "maple", "herbst", "autumn", "kanada"],
    "🍂": ["herbst", "autumn", "laub", "fall", "blätter"],
    "🍄": ["pilz", "mushroom", "wald", "forest"],
    "🦮": ["blindenhund", "guide dog", "assistenzhund", "führhund", "behinderung"],
    "🐕‍🦺": ["assistenzhund", "service dog", "therapiehund", "behinderung", "helfer"],
    "🫎": ["elch", "moose", "hirsch", "kanada", "tier", "geweih"],
    "🫏": ["esel", "donkey", "grautier", "tier", "lasttier"],
    "🦬": ["bison", "büffel", "buffalo", "nordamerika", "prärie"],
    "🐂": ["ochse", "ox", "stier", "rind", "tier", "bauernhof"],
    "🐃": ["wasserbüffel", "water buffalo", "büffel", "asien", "tier"],
    "🐽": ["schweinsnase", "pig nose", "schwein", "pig", "oink", "rüssel"],
    "🦙": ["lama", "llama", "alpaka", "südamerika", "tier"],
    "🦣": ["mammut", "mammoth", "ausgestorben", "eiszeitlich", "prehistoric"],
    "🦫": ["biber", "beaver", "nager", "tier", "damm", "kanada"],
    "🦡": ["dachs", "badger", "tier", "wald"],
    "🦤": ["dodo", "ausgestorben", "vogel", "bird", "mauritius"],
    "🪶": ["feder", "feather", "vogel", "bird", "leicht", "light"],
    "🪽": ["flügel", "wing", "fliegen", "fly", "vogel", "engel"],
    "🦭": ["seehund", "seal", "robbe", "meer", "arktis", "tier"],
    "🐟": ["fisch", "fish", "meer", "sea", "wasser"],
    "🐠": ["tropenfisch", "tropical fish", "bunt", "colorful", "riff", "aquarium"],
    "🐡": ["kugelfisch", "blowfish", "gift", "giftig", "meer", "fisch"],
    "🪸": ["koralle", "coral", "riff", "meer", "ozean", "bunt"],
    "🪼": ["qualle", "jellyfish", "meer", "ozean", "leuchten", "tentakel"],
    "🦗": ["grille", "cricket", "insekt", "zirpen", "chirp"],
    "🪳": ["kakerlake", "cockroach", "insekt", "schädling", "pest"],
    "🪰": ["fliege", "fly", "insekt", "nervend", "sommer"],
    "🪱": ["wurm", "worm", "regenwurm", "erde", "kompost"],
    "🪷": ["lotusblüte", "lotus", "blume", "flower", "asien", "spirituell"],
    "🌺": ["hibiskus", "hibiscus", "blume", "flower", "tropen", "hawaii"],
    "🌿": ["kräuter", "herb", "pflanze", "plant", "grün", "frisch", "kochen"],
    "☘️": ["shamrock", "kleeblatt", "irland", "ireland", "glück", "luck", "st patricks"],
    "🍃": ["blätter", "leaf fluttering in wind", "natur", "nature", "wind", "frisch"],
    "🪹": ["leeres nest", "empty nest", "vogelnest", "nest", "verlassen", "leer"],
    "🪺": ["nest mit eiern", "nest with eggs", "vogelnest", "eier", "frühling", "brüten"],

    # Food & Drink
    "🍇": ["trauben", "grapes", "wein", "wine"],
    "🍈": ["melone", "melon"],
    "🍉": ["wassermelone", "watermelon", "sommer", "summer"],
    "🍊": ["orange", "mandarine", "tangerine", "zitrusfrucht"],
    "🍋": ["zitrone", "lemon", "sauer", "sour"],
    "🍌": ["banane", "banana"],
    "🍍": ["ananas", "pineapple"],
    "🥭": ["mango"],
    "🍎": ["apfel", "apple", "rot", "red", "obst", "fruit"],
    "🍏": ["apfel", "apple", "grün", "green", "obst", "fruit"],
    "🍐": ["birne", "pear", "obst"],
    "🍑": ["pfirsich", "peach", "hintern", "butt"],
    "🍒": ["kirschen", "cherries", "obst"],
    "🍓": ["erdbeere", "strawberry", "obst"],
    "🫐": ["blaubeeren", "blueberries", "heidelbeeren"],
    "🥝": ["kiwi", "obst"],
    "🍅": ["tomate", "tomato"],
    "🥑": ["avocado"],
    "🍆": ["aubergine", "eggplant"],
    "🥔": ["kartoffel", "potato"],
    "🥕": ["karotte", "carrot", "möhre"],
    "🌽": ["mais", "corn"],
    "🌶️": ["chili", "scharf", "hot", "pepper", "peperoni"],
    "🫑": ["paprika", "pepper", "bell pepper"],
    "🥒": ["gurke", "cucumber"],
    "🥬": ["salat", "lettuce", "grünzeug", "blatt"],
    "🥦": ["brokkoli", "broccoli"],
    "🧄": ["knoblauch", "garlic"],
    "🧅": ["zwiebel", "onion"],
    "🍞": ["brot", "bread"],
    "🥐": ["croissant", "hörnchen", "frühstück", "breakfast"],
    "🥖": ["baguette", "brot", "bread", "französisch"],
    "🥨": ["brezel", "pretzel"],
    "🥞": ["pfannkuchen", "pancakes", "frühstück"],
    "🧇": ["waffel", "waffle"],
    "🧀": ["käse", "cheese"],
    "🍖": ["fleisch", "meat", "knochen", "bone"],
    "🍗": ["hähnchen", "chicken", "keule"],
    "🥩": ["steak", "fleisch", "meat"],
    "🥓": ["speck", "bacon"],
    "🍔": ["burger", "hamburger", "fast food", "essen"],
    "🍟": ["pommes", "fries", "chips", "fast food"],
    "🍕": ["pizza"],
    "🌭": ["hotdog", "hot dog", "würstchen", "wurst"],
    "🥪": ["sandwich", "brot", "belegtes brötchen"],
    "🌮": ["taco", "mexikanisch"],
    "🌯": ["burrito", "wrap", "mexikanisch"],
    "🥙": ["döner", "kebab", "pita", "dürüm", "falafel"],
    "🧆": ["falafel"],
    "🥚": ["ei", "egg"],
    "🍳": ["spiegelei", "fried egg", "kochen", "cooking", "bratpfanne", "pfanne"],
    "🥘": ["pfanne", "eintopf", "kochen"],
    "🍲": ["eintopf", "suppe", "stew", "soup", "topf"],
    "🫕": ["fondue", "käsefondue"],
    "🥣": ["müsli", "cereal", "schüssel", "bowl", "frühstück"],
    "🥗": ["salat", "salad", "gesund", "healthy"],
    "🍿": ["popcorn", "kino", "cinema", "film", "movie"],
    "🍱": ["bento", "japanisch", "japanese"],
    "🍙": ["onigiri", "reis", "rice", "japanisch"],
    "🍚": ["reis", "rice"],
    "🍛": ["curry"],
    "🍜": ["ramen", "nudelsuppe", "nudeln", "noodles"],
    "🍝": ["spaghetti", "pasta", "nudeln", "noodles", "italienisch"],
    "🍣": ["sushi", "japanisch", "japanese"],
    "🍤": ["garnele", "shrimp", "garnelen"],
    "🥟": ["dumpling", "teigtasche", "maultasche", "dim sum"],
    "🦀": ["krabbe", "crab", "krebs"],
    "🦞": ["hummer", "lobster"],
    "🦐": ["garnele", "shrimp"],
    "🦑": ["tintenfisch", "squid", "calamari"],
    "🍦": ["eis", "ice cream", "softeis", "eiscreme"],
    "🍧": ["wassereis"],
    "🍨": ["eiscreme", "ice cream", "eis", "eiskugel"],
    "🍩": ["donut", "doughnut"],
    "🍪": ["keks", "cookie"],
    "🎂": ["geburtstagskuchen", "birthday cake", "geburtstag", "birthday", "kuchen", "cake", "torte"],
    "🍰": ["kuchen", "cake", "torte", "sahne"],
    "🧁": ["cupcake", "muffin"],
    "🥧": ["kuchen", "pie", "torte"],
    "🍫": ["schokolade", "chocolate"],
    "🍬": ["bonbon", "candy", "süßigkeit"],
    "🍭": ["lolli", "lollipop", "lutscher"],
    "🍮": ["pudding", "flan", "karamell"],
    "🍯": ["honig", "honey"],
    "🍼": ["babyflasche", "baby bottle", "milch"],
    "🥛": ["milch", "milk", "glas"],
    "☕": ["kaffee", "coffee", "tasse", "cup", "tee", "tea", "heiß", "hot"],
    "🫖": ["teekanne", "teapot", "tee", "tea"],
    "🍵": ["tee", "tea", "matcha", "grüner tee"],
    "🍶": ["sake", "japanisch"],
    "🍾": ["sekt", "champagner", "champagne", "feiern", "party", "prost"],
    "🍷": ["wein", "wine", "rotwein"],
    "🍸": ["cocktail", "martini"],
    "🍹": ["cocktail", "tropical", "drink", "urlaub"],
    "🍺": ["bier", "beer", "prost", "krug"],
    "🍻": ["bier", "beer", "prost", "anstoßen", "cheers"],
    "🥂": ["anstoßen", "cheers", "sekt", "champagner", "prost"],
    "🥃": ["whisky", "whiskey", "schnaps", "bourbon"],
    "🥤": ["getränk", "drink", "cola", "limo", "strohhalm"],
    "🧋": ["bubble tea", "boba"],
    "🧃": ["saft", "juice", "capri sun", "trinkpäckchen"],
    "🧊": ["eis", "ice", "eiswürfel"],
    "🍴": ["besteck", "essen", "eat", "gabel", "messer", "fork", "knife", "restaurant"],
    "🍽️": ["essen", "eat", "restaurant", "teller", "plate", "besteck"],
    "🥄": ["löffel", "spoon"],
    "🔪": ["messer", "knife", "kochen"],
    "🥢": ["stäbchen", "chopsticks", "asiatisch"],
    "🫒": ["olive", "oliven", "öl", "oil", "mediterran", "mittelmeer"],
    "🥥": ["kokosnuss", "coconut", "tropen", "tropic", "kokos", "milch"],
    "🥜": ["erdnuss", "peanut", "nüsse", "nuts", "snack"],
    "🫘": ["bohnen", "beans", "hülsenfrüchte", "legumes", "kaffee"],
    "🌰": ["kastanie", "chestnut", "herbst", "autumn", "eichelhäher"],
    "🫚": ["öl", "ginger", "ingwer", "gewürz", "spice", "kochen"],
    "🫛": ["erbsen", "pea pod", "gemüse", "vegetable", "schote", "erbsenschote"],
    "🫓": ["fladenbrot", "flatbread", "brot", "bread", "backen"],
    "🥯": ["bagel", "brot", "bread", "frühstück", "breakfast"],
    "🫔": ["tamale", "mexikanisch", "mexican", "mais", "gefüllt"],
    "🧈": ["butter", "aufstrich", "backen", "baking", "fett", "fat"],
    "🧂": ["salz", "salt", "würzen", "seasoning", "kochen"],
    "🥫": ["konserve", "canned food", "dose", "can", "haltbar"],
    "🍘": ["reiscracker", "rice cracker", "japanisch", "japanese", "snack"],
    "🍠": ["süßkartoffel", "roasted sweet potato", "yam", "ofen", "japanisch"],
    "🍢": ["oden", "japanisch", "japanese", "street food", "spieß"],
    "🍥": ["fischkuchen", "fish cake", "narutomaki", "japanisch", "ramen"],
    "🥮": ["mondkuchen", "moon cake", "chinesisch", "chinese", "mondfest"],
    "🍡": ["dango", "japanisch", "japanese", "süßigkeit", "spieß", "mochi"],
    "🥠": ["glückskeks", "fortune cookie", "chinesisch", "keks", "weissagung"],
    "🥡": ["take away", "takeout box", "lieferdienst", "delivery", "chinesisch"],
    "🦪": ["auster", "oyster", "meeresfrüchte", "seafood", "perle"],
    "🫗": ["einschenken", "pouring liquid", "gießen", "trinken", "drink"],
    "🧉": ["mate", "matetee", "argentinien", "argentina", "getränk", "südamerika"],
    "🫙": ["glas", "jar", "marmelade", "einmachen", "konservieren", "vorrat"],

    # Travel & Places
    "🌍": ["welt", "world", "erde", "earth", "europa", "europe", "afrika", "africa", "globus"],
    "🌎": ["welt", "world", "erde", "earth", "amerika", "america", "globus"],
    "🌏": ["welt", "world", "erde", "earth", "asien", "asia", "globus"],
    "🗺️": ["weltkarte", "world map", "karte", "map"],
    "🏔️": ["berg", "mountain", "schnee", "snow", "alpen"],
    "⛰️": ["berg", "mountain"],
    "🌋": ["vulkan", "volcano"],
    "🏕️": ["camping", "zelt", "tent", "natur", "wald"],
    "🏖️": ["strand", "beach", "urlaub", "vacation", "meer", "sea", "sonne"],
    "🏜️": ["wüste", "desert"],
    "🏝️": ["insel", "island"],
    "🏗️": ["baustelle", "construction", "kran", "crane", "bauen"],
    "🏠": ["haus", "house", "home", "zuhause"],
    "🏡": ["haus", "house", "home", "garten", "garden"],
    "🏢": ["büro", "office", "gebäude", "building", "firma", "company"],
    "🏥": ["krankenhaus", "hospital", "arzt", "doctor"],
    "🏦": ["bank"],
    "🏨": ["hotel", "übernachtung"],
    "🏪": ["laden", "shop", "store", "einkaufen"],
    "🏫": ["schule", "school", "bildung", "education"],
    "🏭": ["fabrik", "factory", "industrie"],
    "🏰": ["schloss", "castle", "burg"],
    "🏯": ["schloss", "castle", "japanisch", "burg"],
    "💒": ["hochzeit", "wedding", "kirche"],
    "⛪": ["kirche", "church"],
    "🕌": ["moschee", "mosque"],
    "⛲": ["brunnen", "fountain"],
    "🌃": ["nacht", "night", "stadt", "city", "sterne"],
    "🏙️": ["stadt", "city", "skyline"],
    "🌅": ["sonnenaufgang", "sunrise", "sonne", "morgen", "morning"],
    "🌆": ["dämmerung", "dusk", "stadt", "abend"],
    "🌇": ["sonnenuntergang", "sunset", "abend"],
    "🌉": ["brücke", "bridge", "nacht"],
    "🎡": ["riesenrad", "ferris wheel", "jahrmarkt", "kirmes"],
    "🎢": ["achterbahn", "roller coaster", "jahrmarkt", "kirmes"],
    "🚂": ["lok", "lokomotive", "locomotive", "zug", "train", "dampflok"],
    "🚃": ["zug", "train", "wagon", "waggon", "bahn"],
    "🚄": ["zug", "train", "schnellzug", "ice", "tgv", "highspeed"],
    "🚅": ["zug", "train", "shinkansen", "schnellzug"],
    "🚆": ["zug", "train", "bahn"],
    "🚇": ["ubahn", "metro", "underground"],
    "🚈": ["sbahn", "light rail"],
    "🚉": ["bahnhof", "station", "zug", "train"],
    "🚌": ["bus", "reisebus"],
    "🚍": ["bus"],
    "🚑": ["krankenwagen", "ambulance", "rettungswagen", "notfall"],
    "🚒": ["feuerwehr", "fire engine", "feuerwehrauto"],
    "🚓": ["polizei", "police car", "polizeiauto"],
    "🚕": ["taxi", "cab"],
    "🚗": ["auto", "car", "automobile", "pkw", "wagen", "fahrzeug", "vehicle"],
    "🚘": ["auto", "car", "pkw"],
    "🚙": ["suv", "auto", "car", "geländewagen", "jeep"],
    "🛻": ["pickup", "truck", "transporter"],
    "🚚": ["lieferwagen", "delivery", "lkw", "truck", "umzug"],
    "🚛": ["lkw", "truck", "sattelzug", "brummi"],
    "🚜": ["traktor", "tractor", "bauer", "farmer", "landwirtschaft"],
    "🏎️": ["rennwagen", "racing", "formel 1", "f1", "rennauto", "schnell"],
    "🏍️": ["motorrad", "motorcycle", "bike"],
    "🛵": ["roller", "scooter", "moped", "vespa"],
    "🚲": ["fahrrad", "bicycle", "bike", "rad", "radfahren"],
    "🛴": ["roller", "scooter", "kickscooter", "tretroller"],
    "🚏": ["bushaltestelle", "bus stop", "haltestelle"],
    "⛽": ["tankstelle", "gas station", "benzin", "tanken", "sprit"],
    "🚨": ["polizei", "police", "blaulicht", "sirene", "alarm", "notfall"],
    "🚥": ["ampel", "traffic light"],
    "🚦": ["ampel", "traffic light"],
    "🚧": ["baustelle", "construction", "achtung"],
    "⚓": ["anker", "anchor", "schiff", "ship", "hafen"],
    "⛵": ["segelboot", "sailboat", "segeln", "sailing"],
    "🚤": ["speedboot", "speedboat", "boot", "boat", "schnell"],
    "🛳️": ["kreuzfahrt", "cruise", "schiff", "ship"],
    "🚢": ["schiff", "ship", "fähre"],
    "✈️": ["flugzeug", "airplane", "plane", "fliegen", "fly", "reise", "travel"],
    "🛩️": ["flugzeug", "airplane", "klein"],
    "🛫": ["abflug", "departure", "flugzeug", "fliegen"],
    "🛬": ["ankunft", "arrival", "flugzeug", "landen"],
    "🪂": ["fallschirm", "parachute"],
    "🚁": ["hubschrauber", "helicopter", "heli"],
    "🚀": ["rakete", "rocket", "weltraum", "space", "start", "launch"],
    "🛸": ["ufo", "alien", "fliegende untertasse"],
    "🌈": ["regenbogen", "rainbow", "bunt", "colorful"],
    "🔥": ["feuer", "fire", "flamme", "heiß", "hot", "lit", "geil", "krass"],
    "💧": ["tropfen", "drop", "wasser", "water"],
    "🌊": ["welle", "wave", "meer", "sea", "ozean", "ocean", "surfen"],
    "❄️": ["schneeflocke", "snowflake", "winter", "kalt", "cold"],
    "⛄": ["schneemann", "snowman", "winter", "schnee", "snow"],
    "☀️": ["sonne", "sun", "sommer", "summer", "warm", "schön"],
    "🌙": ["mond", "moon", "nacht", "night", "halbmond"],
    "⭐": ["stern", "star", "favorit"],
    "🌟": ["stern", "star", "glitzer", "funkeln"],
    "⚡": ["blitz", "lightning", "strom", "electricity", "energie", "schnell"],
    "☔": ["regen", "rain", "regenschirm", "umbrella", "nass"],
    "🌪️": ["tornado", "wirbelsturm", "sturm"],
    "🗻": ["fuji", "mount fuji", "japan", "japanisch", "berg", "vulkan", "wahrzeichen"],
    "🏞️": ["nationalpark", "national park", "natur", "nature", "landschaft", "usa"],
    "🏟️": ["stadion", "stadium", "sport", "konzert", "arena"],
    "🏛️": ["säulengebäude", "classical building", "antike", "roman", "greek", "museum", "tempel"],
    "🧱": ["ziegel", "brick", "mauer", "wall", "bauen", "build"],
    "🪨": ["felsen", "rock", "stein", "stone", "natur"],
    "🪵": ["holz", "wood", "baumstamm", "log", "natur", "wald"],
    "🛖": ["hütte", "hut", "strohhaus", "thatched", "primitiv", "natur"],
    "🏘️": ["häuser", "houses", "siedlung", "neighborhood", "wohngebiet"],
    "🏚️": ["verfallenes haus", "derelict house", "ruine", "verlassen", "marode"],
    "🏣": ["japanisches postamt", "japanese post office", "post", "japan", "büro"],
    "🏩": ["liebeshotel", "love hotel", "hotel", "romantisch", "japan"],
    "🏬": ["kaufhaus", "department store", "einkaufszentrum", "mall", "laden"],
    "🗼": ["tokyo tower", "tokyo", "japan", "wahrzeichen", "turm", "landmark"],
    "🗽": ["freiheitsstatue", "statue of liberty", "new york", "usa", "wahrzeichen", "liberty"],
    "🛕": ["hinduismus", "hindu temple", "tempel", "temple", "indien", "religion"],
    "🕍": ["synagoge", "synagogue", "judentum", "jewish", "religion", "davidstern"],
    "⛩️": ["schrein", "shinto shrine", "shinto", "japan", "tempel", "torii"],
    "🕋": ["kaaba", "mekka", "mecca", "islam", "muslimisch", "pilger", "hajj"],
    "⛺": ["zelt", "tent", "camping", "outdoor", "natur"],
    "🌁": ["nebel", "foggy", "neblig", "nebelfest", "stadt", "grau"],
    "🌄": ["sonnenaufgang berge", "sunrise over mountains", "morgen", "dawn", "berge", "natur"],
    "🎠": ["karussell", "carousel horse", "vergnügungspark", "kirmes", "pferd"],
    "🛝": ["rutsche", "playground slide", "spielplatz", "kinder", "spaß"],
    "🚊": ["straßenbahn", "tram", "bahn", "öpnv"],
    "🚝": ["monorail", "einschienenbahn", "bahn", "zug", "transport"],
    "🚞": ["bergbahn", "mountain railway", "gebirgsbahn", "zug", "berg"],
    "🚋": ["straßenbahnwagon", "tram car", "straßenbahn", "tram", "öpnv"],
    "🚎": ["obus", "trolleybus", "trolleybus", "bus", "elektrisch", "öpnv"],
    "🚐": ["minibus", "kleinbus", "bus", "transport", "van"],
    "🚔": ["polizei", "oncoming police car", "polizeiauto", "cop", "blaulicht"],
    "🚖": ["taxi", "oncoming taxi", "cab", "gelb", "yellow"],
    "🛺": ["rikscha", "auto rickshaw", "tuk tuk", "asien", "thailand", "transport"],
    "🛣️": ["autobahn", "motorway", "straße", "highway", "freeway"],
    "🛟": ["rettungsring", "ring buoy", "sicherheit", "meer", "retten", "safety"],
    "⛴️": ["fähre", "ferry", "schiff", "ship", "überfahrt"],
    "🛥️": ["motorboot", "motor boat", "boot", "boat", "schnell"],
    "💺": ["sitz", "seat", "sitzplatz", "flugzeug", "kino", "stuhl"],
    "🚟": ["hängebahn", "suspension railway", "bahn", "transport", "schwebebahn"],
    "🚠": ["seilbahn", "mountain cableway", "berge", "gondel", "gondola"],
    "🚡": ["luftseilbahn", "aerial tramway", "gondel", "gondola", "seilbahn", "berge"],
    "🛰️": ["satellit", "satellite", "weltraum", "space", "orbit", "kommunikation"],
    "🌠": ["sternschnuppe", "shooting star", "wunsch", "wish", "sterne", "nachts"],
    "🌌": ["milchstraße", "milky way", "galaxie", "galaxy", "weltraum", "space", "universum"],
    "⛱️": ["sonnenschirm", "umbrella on ground", "strand", "beach", "urlaub", "sommer"],
    "🎆": ["feuerwerk", "fireworks", "silvester", "neujahr", "feiern", "celebration"],
    "🎇": ["wunderkerze", "sparkler", "feuerwerk", "silvester", "glitzer"],
    "🎑": ["mondfest", "moon viewing ceremony", "japan", "mondschau", "herbst", "otsukimi"],
    "🌑": ["neumond", "new moon", "mond", "moon", "dunkel", "nacht"],
    "🌒": ["zunehmend", "waxing crescent moon", "mond", "moon", "sichelmond"],
    "🌓": ["halbmond", "first quarter moon", "mond", "moon", "viertelmond"],
    "🌔": ["zunehmend", "waxing gibbous moon", "mond", "moon", "fast voll"],
    "🌕": ["vollmond", "full moon", "mond", "moon", "hell", "bright"],
    "🌖": ["abnehmend", "waning gibbous moon", "mond", "moon", "phase"],
    "🌗": ["halbmond", "last quarter moon", "mond", "moon", "viertelmond"],
    "🌘": ["abnehmend", "waning crescent moon", "mond", "moon", "sichelmond"],
    "🌚": ["neumond gesicht", "new moon face", "mond", "moon", "dunkel", "gruselig"],
    "🌛": ["mond gesicht", "first quarter moon face", "mond", "moon", "halbmond"],
    "🌜": ["mond gesicht", "last quarter moon face", "mond", "moon", "halbmond"],
    "🌝": ["vollmond gesicht", "full moon face", "mond", "moon", "lächeln"],
    "🌞": ["sonne gesicht", "sun with face", "sonne", "sun", "lächeln", "sommer"],
    "🌤️": ["bewölkt", "sun behind small cloud", "sonne", "sun", "wolke", "cloud", "wetter"],
    "⛅": ["halbbedeckt", "sun behind cloud", "sonne", "wolke", "wetter", "bedeckt"],
    "🌥️": ["bewölkt", "sun behind large cloud", "sonne", "wolke", "bedeckt", "wetter"],
    "🌦️": ["regen sonne", "sun behind rain cloud", "regen", "rain", "wechselhaft", "wetter"],
    "🌧️": ["regen", "cloud with rain", "regenwolke", "nass", "wetter", "tropfen"],
    "🌨️": ["schnee", "cloud with snow", "schneewolke", "winter", "kalt", "wetter"],
    "🌩️": ["gewitter", "cloud with lightning", "blitz", "lightning", "sturm", "donner"],
    "🌫️": ["nebel", "fog", "neblig", "trüb", "sicht", "wetter"],
    "🌬️": ["wind", "wind face", "blasen", "blow", "sturm", "kalt", "wetter"],
    "🌀": ["wirbel", "cyclone", "taifun", "typhoon", "sturm", "tornado", "spirale"],
    "☂️": ["regenschirm", "umbrella", "regen", "rain", "schutz", "protection"],
    "☃️": ["schneemann", "snowman", "schnee", "snow", "winter", "weihnachten"],
    "☄️": ["komet", "comet", "meteor", "weltraum", "space", "einschlag"],

    # Activities
    "🎃": ["halloween", "kürbis", "pumpkin"],
    "🎄": ["weihnachten", "christmas", "weihnachtsbaum", "tannenbaum"],
    "✨": ["funkeln", "sparkle", "glitzer", "magic", "neu", "new", "sterne"],
    "🎈": ["ballon", "balloon", "party", "geburtstag", "birthday"],
    "🎉": ["party", "feier", "geburtstag", "gratulation", "congratulations", "yay"],
    "🎊": ["konfetti", "confetti", "party", "feier"],
    "🎁": ["geschenk", "gift", "present", "geburtstag", "weihnachten"],
    "🏆": ["pokal", "trophy", "gewinner", "winner", "sieg", "champion"],
    "🏅": ["medaille", "medal", "gewinner", "sport"],
    "🥇": ["gold", "erster", "first", "gewinner", "medaille"],
    "🥈": ["silber", "silver", "zweiter", "second", "medaille"],
    "🥉": ["bronze", "dritter", "third", "medaille"],
    "⚽": ["fußball", "football", "soccer", "ball", "sport"],
    "⚾": ["baseball", "sport", "ball"],
    "🏀": ["basketball", "sport", "ball"],
    "🏐": ["volleyball", "sport", "ball"],
    "🏈": ["american football", "sport", "ball", "nfl"],
    "🎾": ["tennis", "sport", "ball", "schläger"],
    "🏓": ["tischtennis", "ping pong", "sport"],
    "🏸": ["badminton", "federball", "sport"],
    "🥊": ["boxen", "boxing", "handschuh", "sport", "kampf"],
    "🥋": ["kampfsport", "martial arts", "karate", "judo"],
    "⛳": ["golf", "sport"],
    "🎣": ["angeln", "fishing", "fisch"],
    "🎿": ["ski", "skiing", "winter", "sport", "schnee"],
    "🛷": ["schlitten", "sled", "winter", "schnee"],
    "🎯": ["ziel", "target", "treffer", "bullseye", "dart", "darts"],
    "🎮": ["videospiel", "gaming", "controller", "zocken", "spielen", "game", "konsole"],
    "🕹️": ["joystick", "gaming", "arcade", "spielen"],
    "🎰": ["spielautomat", "slot machine", "casino", "glücksspiel"],
    "🎲": ["würfel", "dice", "spiel", "game", "zufall"],
    "🧩": ["puzzle", "rätsel"],
    "🧸": ["teddy", "teddybär", "kuscheltier", "plüsch"],
    "🪩": ["discokugel", "disco", "party", "mirror ball", "tanzen"],
    "♟️": ["schach", "chess", "bauer", "pawn"],
    "🎭": ["theater", "maske", "drama", "comedy"],
    "🎨": ["kunst", "art", "malen", "paint", "palette", "künstler"],
    "🧵": ["faden", "thread", "nähen", "sewing"],
    "🧶": ["wolle", "yarn", "stricken", "knitting"],
    "🎵": ["musik", "music", "note"],
    "🎶": ["musik", "music", "noten", "notes"],
    "🎤": ["mikrofon", "microphone", "singen", "sing", "karaoke"],
    "🎧": ["kopfhörer", "headphones", "musik", "music"],
    "📻": ["radio"],
    "🎷": ["saxophon", "saxophone", "jazz", "musik"],
    "🎸": ["gitarre", "guitar", "rock", "musik"],
    "🎹": ["klavier", "piano", "keyboard", "musik"],
    "🎺": ["trompete", "trumpet", "musik"],
    "🎻": ["geige", "violin", "musik"],
    "🥁": ["trommel", "drum", "schlagzeug", "musik"],
    "🎆": ["feuerwerk", "fireworks", "silvester", "neujahr", "feiern", "celebration"],
    "🎇": ["wunderkerze", "sparkler", "feuerwerk", "silvester", "glitzer"],
    "🧨": ["böller", "firecracker", "feuerwerk", "silvester", "china", "knall"],
    "🎋": ["bambusbaum", "tanabata tree", "japan", "festival", "tanabata"],
    "🎍": ["kieferdekoration", "pine decoration", "japan", "neujahr", "kadomatsu"],
    "🎎": ["japanische puppen", "japanese dolls", "japan", "hinamatsuri", "puppen", "festival"],
    "🎏": ["koinobori", "carp streamer", "japan", "karpfen", "kindertag", "festival"],
    "🎐": ["windspiel", "wind chime", "japan", "sommer", "festival", "furin"],
    "🎑": ["mondfest", "moon viewing ceremony", "japan", "herbst", "otsukimi"],
    "🧧": ["rotes kuvert", "red envelope", "china", "neujahr", "glücksgeld", "hongbao"],
    "🎀": ["schleife", "ribbon", "geschenk", "gift", "rosa", "pink"],
    "🎗️": ["schleife", "reminder ribbon", "bewusstsein", "awareness", "erinnerung"],
    "🎟️": ["eintrittskarten", "admission tickets", "kino", "konzert", "veranstaltung"],
    "🎫": ["ticket", "eintrittskarte", "kino", "konzert", "veranstaltung", "event"],
    "🎖️": ["militärmedaille", "military medal", "auszeichnung", "orden", "verdienst"],
    "🥎": ["softball", "sport", "ball", "baseball"],
    "🏉": ["rugby", "rugby football", "sport", "ball", "oval"],
    "🥏": ["frisbee", "flying disc", "scheibe", "sport", "werfen"],
    "🎳": ["bowling", "kegeln", "kegel", "sport", "ball", "pins"],
    "🏏": ["kricket", "cricket game", "sport", "bat", "schläger"],
    "🏑": ["feldhockey", "field hockey", "hockey", "sport", "schläger"],
    "🏒": ["eishockey", "ice hockey", "hockey", "sport", "eis", "puck"],
    "🥍": ["lacrosse", "sport", "netz", "schläger"],
    "🥅": ["tor", "goal net", "netz", "net", "sport", "fußball"],
    "⛸️": ["schlittschuhe", "ice skate", "eislaufen", "eis", "winter", "sport"],
    "🤿": ["tauchermaske", "diving mask", "tauchen", "diving", "schnorcheln", "sport"],
    "🎽": ["sport shirt", "running shirt", "laufen", "running", "sport", "trikot"],
    "🥌": ["curling", "curling stone", "stein", "winter", "sport", "eis"],
    "🪀": ["jojo", "yo-yo", "spielzeug", "toy", "drehen", "spin"],
    "🪁": ["drachen", "kite", "fliegen", "fly", "wind", "spielzeug"],
    "🔫": ["wasserpistole", "water pistol", "spielzeug", "toy", "pistole", "gun"],
    "🎱": ["billard", "pool 8 ball", "8-ball", "snooker", "sport", "ball"],
    "🔮": ["kristallkugel", "crystal ball", "wahrsagung", "fortune", "magie", "magic"],
    "🪄": ["zauberstab", "magic wand", "magie", "magic", "zauberer", "wizard"],
    "🪅": ["piñata", "mexico", "mexikanisch", "feiern", "party", "süßigkeiten"],
    "🪆": ["matroschka", "nesting dolls", "russland", "russia", "puppe", "doll"],
    "♠️": ["pik", "spade suit", "karten", "cards", "spielkarte", "poker"],
    "♥️": ["herz", "heart suit", "karten", "cards", "spielkarte", "poker"],
    "♦️": ["karo", "diamond suit", "karten", "cards", "spielkarte", "poker"],
    "♣️": ["kreuz", "club suit", "karten", "cards", "spielkarte", "poker"],
    "🃏": ["joker", "joker card", "karte", "poker", "wildcard"],
    "🀄": ["mahjong", "mahjong red dragon", "rot", "drache", "china", "spiel"],
    "🎴": ["hanafuda", "flower playing cards", "japan", "karten", "blumen", "spiel"],
    "🖼️": ["gemälde", "framed picture", "bild", "kunst", "art", "rahmen", "galerie"],
    "🪡": ["nähnadel", "sewing needle", "nähen", "faden", "handarbeit"],
    "🪢": ["knoten", "knot", "binden", "seil", "rope"],
    "🎼": ["notenblatt", "musical score", "musik", "noten", "partitur", "komponist"],
    "🎙️": ["studiomikrofon", "studio microphone", "podcast", "radio", "aufnahme"],
    "🎚️": ["regler", "level slider", "audio", "mischer", "mixer", "studio"],
    "🎛️": ["regler", "control knobs", "studio", "mischer", "mixer", "einstellungen"],
    "🪗": ["akkordeon", "accordion", "musik", "instrument", "quetschkommode"],
    "🪕": ["banjo", "musik", "instrument", "country", "bluegrass"],
    "🪘": ["trommel", "long drum", "musik", "instrument", "afrika", "rhythmus"],
    "🪇": ["maracas", "rassel", "instrument", "musik", "lateinamerika", "rhythmus"],
    "🪈": ["flöte", "flute", "musik", "instrument", "blockflöte"],

    # Objects
    "👓": ["brille", "glasses"],
    "🕶️": ["sonnenbrille", "sunglasses", "cool"],
    "👔": ["krawatte", "tie", "business", "arbeit", "formal"],
    "👕": ["tshirt", "t-shirt", "shirt", "oberteil"],
    "👖": ["jeans", "hose", "pants"],
    "👗": ["kleid", "dress"],
    "👘": ["kimono", "japanisch"],
    "👙": ["bikini", "strand", "beach", "sommer"],
    "👟": ["schuhe", "sneaker", "turnschuh", "sport"],
    "👞": ["schuhe", "shoes", "herrenschuh"],
    "👠": ["high heels", "absatzschuhe", "schuh"],
    "👑": ["krone", "crown", "könig", "king", "königin", "queen"],
    "🎩": ["zylinder", "top hat", "gentleman", "hut"],
    "🎓": ["abschluss", "graduation", "uni", "studium", "doktorhut"],
    "🧢": ["kappe", "cap", "mütze", "basecap"],
    "🧿": ["nazar", "böser blick", "evil eye", "amulett", "türkisch", "glück", "schutz", "protection"],
    "🪬": ["hamsa", "hand gottes", "fatimas hand", "amulett", "schutz", "protection", "böser blick"],
    "💍": ["ring", "verlobung", "engagement", "hochzeit", "wedding", "diamant"],
    "💎": ["diamant", "diamond", "edelstein", "gem", "juwel"],
    "📱": ["handy", "smartphone", "phone", "telefon", "mobile"],
    "📲": ["handy", "phone", "download"],
    "☎️": ["telefon", "telephone", "phone", "anrufen"],
    "💻": ["laptop", "computer", "notebook", "pc"],
    "🖥️": ["computer", "desktop", "pc", "bildschirm", "monitor"],
    "🖨️": ["drucker", "printer"],
    "⌨️": ["tastatur", "keyboard"],
    "🖱️": ["maus", "mouse", "computer"],
    "💽": ["cd", "disk", "speicher"],
    "💾": ["diskette", "floppy", "speichern", "save"],
    "💿": ["cd", "dvd", "disk"],
    "📀": ["dvd", "cd", "film"],
    "🎥": ["kamera", "camera", "film", "movie"],
    "📷": ["kamera", "camera", "foto", "photo"],
    "📸": ["kamera", "camera", "foto", "photo", "blitz", "flash"],
    "📹": ["videokamera", "video camera", "film"],
    "📺": ["fernseher", "tv", "television", "fernsehen"],
    "🔍": ["suchen", "search", "lupe", "magnifying glass"],
    "🔎": ["suchen", "search", "lupe"],
    "💡": ["glühbirne", "light bulb", "idee", "idea", "licht", "light"],
    "🔦": ["taschenlampe", "flashlight", "licht"],
    "📖": ["buch", "book", "lesen", "read"],
    "📕": ["buch", "book"],
    "📗": ["buch", "book"],
    "📘": ["buch", "book"],
    "📚": ["bücher", "books", "lesen", "read", "bibliothek", "library"],
    "📝": ["notiz", "memo", "schreiben", "write", "note"],
    "📄": ["dokument", "document", "seite", "page", "datei", "file"],
    "📰": ["zeitung", "newspaper", "nachrichten", "news"],
    "💰": ["geld", "money", "beutel", "bag", "reich"],
    "💴": ["geld", "yen", "japanisch"],
    "💵": ["geld", "dollar", "schein", "bill"],
    "💶": ["geld", "euro", "schein"],
    "💷": ["geld", "pfund", "pound"],
    "💸": ["geld", "money", "weg", "ausgeben", "spend", "teuer"],
    "💳": ["kreditkarte", "credit card", "karte", "bezahlen", "pay"],
    "✉️": ["brief", "letter", "email", "mail", "post"],
    "📧": ["email", "e-mail", "mail", "nachricht"],
    "📦": ["paket", "package", "box", "lieferung", "delivery"],
    "📫": ["briefkasten", "mailbox", "post"],
    "📮": ["briefkasten", "postbox", "post"],
    "✏️": ["bleistift", "pencil", "schreiben"],
    "🖊️": ["kugelschreiber", "pen", "stift", "schreiben"],
    "🖌️": ["pinsel", "paintbrush", "malen", "kunst"],
    "📅": ["kalender", "calendar", "termin", "datum", "date"],
    "📆": ["kalender", "calendar"],
    "📋": ["klemmbrett", "clipboard", "liste", "list"],
    "📌": ["pinnnadel", "pushpin", "pin", "merken"],
    "📎": ["büroklammer", "paperclip", "klammer"],
    "✂️": ["schere", "scissors", "schneiden", "cut"],
    "🔒": ["schloss", "lock", "sicher", "secure", "gesperrt"],
    "🔓": ["offen", "unlock", "open", "entsperrt"],
    "🔑": ["schlüssel", "key"],
    "🗝️": ["schlüssel", "key", "alt", "old"],
    "🔨": ["hammer", "werkzeug", "tool", "bauen"],
    "🪓": ["axt", "axe", "holz", "wood"],
    "🔧": ["schraubenschlüssel", "wrench", "werkzeug", "tool", "reparieren"],
    "🪛": ["schraubenzieher", "screwdriver", "werkzeug"],
    "🔩": ["schraube", "screw", "mutter", "bolt"],
    "⚙️": ["zahnrad", "gear", "einstellungen", "settings", "mechanik"],
    "🧰": ["werkzeugkasten", "toolbox", "werkzeug"],
    "🧲": ["magnet"],
    "🪜": ["leiter", "ladder"],
    "🧪": ["reagenzglas", "test tube", "labor", "chemie", "science"],
    "🧬": ["dna", "genetik", "gen", "biologie"],
    "🔬": ["mikroskop", "microscope", "labor", "science"],
    "🔭": ["teleskop", "telescope", "sterne", "astronomie"],
    "💉": ["spritze", "syringe", "impfung", "vaccine", "arzt", "nadel"],
    "💊": ["pille", "pill", "tablette", "medizin", "medicine", "arzt"],
    "🩹": ["pflaster", "bandaid", "band-aid", "wunde"],
    "🩺": ["stethoskop", "stethoscope", "arzt", "doctor"],
    "🚪": ["tür", "door", "eingang", "ausgang"],
    "🪞": ["spiegel", "mirror"],
    "🪟": ["fenster", "window"],
    "🛏️": ["bett", "bed", "schlafen", "sleep"],
    "🛋️": ["sofa", "couch", "wohnzimmer"],
    "🪑": ["stuhl", "chair", "sitzen"],
    "🚽": ["toilette", "toilet", "klo", "wc"],
    "🚿": ["dusche", "shower", "duschen", "bad"],
    "🛁": ["badewanne", "bathtub", "bad", "baden"],
    "🧹": ["besen", "broom", "kehren", "putzen"],
    "🧺": ["korb", "basket", "wäsche", "laundry"],
    "🧻": ["klopapier", "toilet paper", "toilettenpapier"],
    "🧼": ["seife", "soap", "waschen"],
    "🪥": ["zahnbürste", "toothbrush", "zähne"],
    "🧽": ["schwamm", "sponge", "putzen"],
    "🧯": ["feuerlöscher", "fire extinguisher"],
    "🛒": ["einkaufswagen", "shopping cart", "einkaufen", "supermarkt"],
    "🥽": ["schutzbrille", "goggles", "labor", "schutz", "sicherheit", "schweißen"],
    "🥼": ["laborkittel", "lab coat", "labor", "arzt", "wissenschaft", "science", "weißer kittel"],
    "🦺": ["sicherheitsweste", "safety vest", "schutz", "baustelle", "construction", "warnweste"],
    "🧣": ["schal", "scarf", "winter", "kalt", "kleidung"],
    "🧤": ["handschuhe", "gloves", "winter", "kalt", "kleidung"],
    "🧥": ["mantel", "coat", "winter", "jacke", "jacket", "kleidung"],
    "🧦": ["socken", "socks", "kleidung", "füße", "strümpfe"],
    "🥻": ["sari", "indisch", "india", "kleidung", "traditionell"],
    "🩱": ["badeanzug", "one-piece swimsuit", "schwimmen", "strand", "beach", "sport"],
    "🩲": ["unterwäsche", "briefs", "slip", "unterhose", "kleidung"],
    "🩳": ["shorts", "kurze hose", "sommer", "sport", "kleidung"],
    "👚": ["damenoberteil", "woman's clothes", "shirt", "kleidung", "bluse"],
    "🪭": ["fächer", "folding hand fan", "sommer", "japan", "kühlen", "fan"],
    "👛": ["portemonnaie", "purse", "geldbörse", "wallet", "geld"],
    "👜": ["handtasche", "handbag", "tasche", "bag", "mode"],
    "👝": ["kleine tasche", "clutch bag", "tasche", "bag", "abend"],
    "🛍️": ["einkaufstüten", "shopping bags", "einkaufen", "laden", "store", "mode"],
    "🎒": ["rucksack", "backpack", "schule", "reise", "travel", "tasche"],
    "🩴": ["badeschlappe", "thong sandal", "flip flop", "sommer", "strand", "schuh"],
    "🥾": ["wanderschuh", "hiking boot", "wandern", "outdoor", "natur", "schuh"],
    "🥿": ["ballerina", "flat shoe", "schuh", "flach", "mode"],
    "👡": ["sandale", "woman's sandal", "absatz", "heel", "schuh", "mode"],
    "🩰": ["ballettschuhe", "ballet shoes", "tanz", "dance", "ballett", "ballet"],
    "👢": ["stiefel", "woman's boot", "mode", "kleidung", "schuh"],
    "🪮": ["haarkamm", "hair pick", "afro", "haare", "frisur", "kamm"],
    "👒": ["damenhut", "woman's hat", "hut", "hat", "mode", "sommer"],
    "🪖": ["militärhelm", "military helmet", "soldat", "armee", "army", "schutz"],
    "⛑️": ["rettungshelm", "rescue worker's helmet", "helm", "sicherheit", "bauhelm"],
    "📿": ["gebetskette", "prayer beads", "religion", "beten", "mala", "rosenkranz"],
    "💄": ["lippenstift", "lipstick", "make-up", "schminken", "rouge", "mode"],
    "📞": ["telefonhörer", "telephone receiver", "telefon", "anruf", "call"],
    "📟": ["pager", "beeper", "altmodisch", "retro", "nachricht"],
    "📠": ["fax", "fax machine", "büro", "office", "dokument"],
    "🔋": ["akku", "battery", "energie", "energy", "laden", "charge"],
    "🪫": ["leer", "low battery", "akku leer", "energy low", "schwach"],
    "🔌": ["stecker", "electric plug", "strom", "elektrisch", "aufladen", "verbinden"],
    "🖲️": ["trackball", "maus", "mouse", "computer", "zeiger"],
    "🧮": ["rechner", "abacus", "abakus", "rechnen", "zahlen", "mathematik"],
    "🎞️": ["filmstreifen", "film frames", "film", "kino", "foto", "analog"],
    "📽️": ["filmprojektor", "film projector", "kino", "film", "projektor"],
    "🎬": ["filmklappe", "clapper board", "kino", "film", "dreh", "action"],
    "📼": ["videokassette", "videocassette", "retro", "vhs", "video", "cassette"],
    "🕯️": ["kerze", "candle", "licht", "romantisch", "romantik", "stimmung"],
    "🏮": ["rotes lampion", "red paper lantern", "china", "japan", "laterne", "licht"],
    "🪔": ["öllampe", "diya lamp", "indien", "diwali", "licht", "fest"],
    "📔": ["notizbuch", "notebook with decorative cover", "buch", "heft", "schreiben"],
    "📙": ["oranges buch", "orange book", "buch", "lesen", "notizbuch"],
    "📓": ["notizbuch", "notebook", "heft", "schreiben", "schule"],
    "📒": ["hauptbuch", "ledger", "buchhaltung", "büro", "aufzeichnung"],
    "📃": ["seite mit umschlag", "page with curl", "dokument", "papier", "brief"],
    "📜": ["schriftrolle", "scroll", "dokument", "alt", "gesetz", "urkunde"],
    "🗞️": ["zeitung", "rolled-up newspaper", "nachrichten", "news", "presse"],
    "📑": ["registerblätter", "bookmark tabs", "dokument", "register", "tabs"],
    "🔖": ["lesezeichen", "bookmark", "buch", "merken", "markieren"],
    "🏷️": ["etikett", "label", "tag", "preis", "aufkleber"],
    "🪙": ["münze", "coin", "geld", "money", "gold", "silver"],
    "🧾": ["kassenzettel", "receipt", "quittung", "einkauf", "kosten"],
    "📨": ["eingehende post", "incoming envelope", "brief", "email", "post", "eingang"],
    "📩": ["brief mit pfeil", "envelope with arrow", "email", "senden", "post"],
    "📤": ["ausgangskorb", "outbox tray", "senden", "ausgang", "post"],
    "📥": ["eingangskorb", "inbox tray", "empfangen", "eingang", "post"],
    "📪": ["geschlossener briefkasten", "closed mailbox with lowered flag", "post", "mailbox"],
    "📬": ["offener briefkasten", "open mailbox with raised flag", "post", "brief"],
    "📭": ["offener briefkasten leer", "open mailbox with lowered flag", "post", "mailbox"],
    "🗳️": ["wahlurne", "ballot box", "wahl", "vote", "abstimmung", "demokratie"],
    "✒️": ["tintenfeder", "black nib", "schreiben", "stift", "feder", "tinte"],
    "🖋️": ["füllfeder", "fountain pen", "füller", "stift", "schreiben", "tinte"],
    "🖍️": ["wachsmalstift", "crayon", "malen", "kinder", "bunt", "zeichnen"],
    "📁": ["ordner", "file folder", "datei", "computer", "ablage"],
    "📂": ["offener ordner", "open file folder", "datei", "computer", "ablage"],
    "🗂️": ["register", "card index dividers", "ordnen", "ablage", "büro"],
    "🗒️": ["spiralnotizblock", "spiral notepad", "notizbuch", "schreiben", "büro"],
    "🗓️": ["spiralkalender", "spiral calendar", "kalender", "termin", "datum"],
    "📇": ["kartei", "card index", "adresse", "kontakt", "büro", "register"],
    "📈": ["aufwärtstrend", "chart increasing", "statistik", "wachstum", "aktien", "erfolg"],
    "📉": ["abwärtstrend", "chart decreasing", "statistik", "verlust", "aktien", "absturz"],
    "📊": ["balkendiagramm", "bar chart", "statistik", "diagramm", "chart", "daten"],
    "📍": ["pinnnadel", "round pushpin", "pin", "ort", "standort", "karte"],
    "🖇️": ["büroklammern", "linked paperclips", "klammer", "verbinden", "büro"],
    "📏": ["lineal", "straight ruler", "messen", "schule", "zeichnen"],
    "📐": ["geodreieck", "triangular ruler", "messen", "schule", "geometrie"],
    "🗃️": ["karteikasten", "card file box", "ablage", "ordnen", "archiv"],
    "🗄️": ["aktenschrank", "file cabinet", "büro", "ablage", "archiv", "ordner"],
    "🗑️": ["papierkorb", "wastebasket", "löschen", "delete", "müll", "trash"],
    "🔏": ["gesperrt mit stift", "locked with pen", "geheim", "privat", "sicherheit"],
    "🔐": ["gesperrt mit schlüssel", "locked with key", "sicherheit", "privat", "geheim"],
    "⛏️": ["spitzhacke", "pick", "bergbau", "mining", "minecraft", "hacken"],
    "⚒️": ["hammer und spitzhacke", "hammer and pick", "werkzeug", "bergbau", "schmied"],
    "🛠️": ["werkzeug", "hammer and wrench", "reparatur", "repair", "bauen"],
    "🗡️": ["dolch", "dagger", "messer", "waffe", "mittelalter"],
    "⚔️": ["gekreuzte schwerter", "crossed swords", "krieg", "kampf", "waffe", "ritter"],
    "💣": ["bombe", "bomb", "explosion", "boom", "gefahr"],
    "🪃": ["bumerang", "boomerang", "australien", "werfen", "rückwurf"],
    "🏹": ["pfeil und bogen", "bow and arrow", "bogenschießen", "jäger", "hunter"],
    "🛡️": ["schild", "shield", "schutz", "rüstung", "ritter", "verteidigung"],
    "🪚": ["handsäge", "carpentry saw", "säge", "holz", "werkzeug", "zimmermann"],
    "🗜️": ["schraubzwinge", "clamp", "klemme", "festhalten", "werkzeug"],
    "⚖️": ["waage", "balance scale", "gerechtigkeit", "justice", "gleichgewicht", "recht"],
    "🦯": ["weißer stock", "white cane", "blind", "blindheit", "führstock", "sehbehindert"],
    "🔗": ["link", "kette", "chain", "verbinden", "verbindung", "url"],
    "⛓️": ["ketten", "chains", "gefangen", "prisoner", "metall", "stahl"],
    "🪝": ["haken", "hook", "aufhängen", "angeln", "fishing"],
    "⚗️": ["destillation", "alembic", "chemie", "labor", "science", "alchemie"],
    "🧫": ["petrischale", "petri dish", "labor", "biologie", "wissenschaft", "bakterien"],
    "📡": ["antenne", "satellite antenna", "signal", "empfang", "kommunikation", "radio"],
    "🩸": ["blut", "drop of blood", "verletzung", "donor", "spende", "medizin"],
    "🩼": ["krücke", "crutch", "verletzung", "behinderung", "laufen", "bein"],
    "🩻": ["röntgen", "x-ray", "knochen", "medizin", "arzt", "diagnostik"],
    "🛗": ["aufzug", "elevator", "lift", "fahrstuhl", "gebäude"],
    "🪠": ["saugglocke", "plunger", "toilette", "toilet", "klempner", "verstopft"],
    "🪤": ["mausefalle", "mouse trap", "falle", "trap", "maus", "mouse"],
    "🪒": ["rasierklinge", "razor", "rasieren", "shave", "bartpflege"],
    "🧴": ["lotion", "lotion bottle", "creme", "körperpflege", "flasche"],
    "🧷": ["sicherheitsnadel", "safety pin", "nadel", "befestigen", "kleidung"],
    "🪣": ["eimer", "bucket", "wasser", "reinigung", "cleaning"],
    "🫧": ["blasen", "bubbles", "seife", "soap", "sprudeln", "soda"],

    # Symbols
    "⚠️": ["warnung", "warning", "achtung", "vorsicht", "caution"],
    "⛔": ["verboten", "stop", "no entry", "halt"],
    "🚫": ["verboten", "prohibited", "nein", "no", "stop"],
    "✅": ["fertig", "done", "check", "erledigt", "ok", "ja", "yes", "richtig", "correct", "häkchen"],
    "❌": ["falsch", "wrong", "nein", "no", "fehler", "error", "kreuz", "cross"],
    "❓": ["frage", "question"],
    "❗": ["achtung", "wichtig", "important", "ausrufezeichen"],
    "♻️": ["recycling", "umwelt", "grün"],
    "➡️": ["rechts", "right", "pfeil", "arrow", "weiter", "next"],
    "⬅️": ["links", "left", "pfeil", "arrow", "zurück", "back"],
    "⬆️": ["oben", "up", "pfeil", "arrow", "hoch"],
    "⬇️": ["unten", "down", "pfeil", "arrow", "runter"],
    "🔴": ["rot", "red", "kreis", "circle"],
    "🟠": ["orange", "kreis", "circle"],
    "🟡": ["gelb", "yellow", "kreis", "circle"],
    "🟢": ["grün", "green", "kreis", "circle"],
    "🔵": ["blau", "blue", "kreis", "circle"],
    "🟣": ["lila", "purple", "violett", "kreis", "circle"],
    "⚫": ["schwarz", "black", "kreis", "circle"],
    "⚪": ["weiß", "white", "kreis", "circle"],
    "©️": ["copyright"],
    "®️": ["registered", "marke"],
    "™️": ["trademark", "marke"],
    "🏧": ["geldautomat", "atm sign", "bankgeldautomat", "geld", "abheben", "bank"],
    "🚮": ["abfalleimer", "litter in bin sign", "müll", "hinwerfen", "sauber", "abfall"],
    "🚰": ["trinkwasser", "potable water", "wasser", "trinken", "wasserhahn"],
    "♿": ["rollstuhl", "wheelchair symbol", "behinderung", "barrierefrei", "accessible"],
    "🚹": ["herren", "men's room", "männertoilette", "wc", "herrentoilette"],
    "🚺": ["damen", "women's room", "damentoilette", "wc", "frauentoilette"],
    "🚻": ["toilette", "restroom", "wc", "sanitär", "klo"],
    "🚼": ["baby", "baby symbol", "wickeln", "kinderwagen", "wickelraum"],
    "🚾": ["wc", "water closet", "toilette", "klo", "sanitär"],
    "🛂": ["passkontrolle", "passport control", "grenze", "flughafen", "zoll"],
    "🛃": ["zoll", "customs", "grenze", "flughafen", "kontrolle"],
    "🛄": ["gepäck", "baggage claim", "koffer", "flughafen", "gepäckausgabe"],
    "🛅": ["gepäckaufbewahrung", "left luggage", "koffer", "flughafen", "aufbewahrung"],
    "🚸": ["kinder", "children crossing", "schulweg", "überqueren", "verkehr"],
    "🚳": ["kein fahrrad", "no bicycles", "verboten", "prohibited", "fahrradverbot"],
    "🚭": ["rauchen verboten", "no smoking", "rauchverbot", "verboten", "zigarette"],
    "🚯": ["kein müll", "no littering", "littering verboten", "verboten", "sauber"],
    "🚱": ["kein trinkwasser", "non-potable water", "wasser", "verboten", "kein trinken"],
    "🚷": ["keine fußgänger", "no pedestrians", "verboten", "überqueren"],
    "📵": ["kein handy", "no mobile phones", "handyverbot", "verboten", "smartphone"],
    "🔞": ["kein zutritt unter 18", "no one under eighteen", "verboten", "jugendschutz", "18+"],
    "☢️": ["radioaktiv", "radioactive", "strahlung", "gefahr", "atom", "nuclear"],
    "☣️": ["biogefährdend", "biohazard", "gefahr", "seuche", "biologisch"],
    "↗️": ["pfeil oben rechts", "up-right arrow", "diagonal", "richtung", "nordost"],
    "↘️": ["pfeil unten rechts", "down-right arrow", "diagonal", "richtung", "südost"],
    "↙️": ["pfeil unten links", "down-left arrow", "diagonal", "richtung", "südwest"],
    "↖️": ["pfeil oben links", "up-left arrow", "diagonal", "richtung", "nordwest"],
    "↕️": ["pfeil hoch runter", "up-down arrow", "vertikal", "richtung", "vertical"],
    "↔️": ["pfeil links rechts", "left-right arrow", "horizontal", "richtung"],
    "↩️": ["pfeil zurück", "right arrow curving left", "zurück", "antwort", "reply"],
    "↪️": ["pfeil weiter", "left arrow curving right", "weiterleiten", "forward"],
    "⤴️": ["pfeil nach oben rechts", "right arrow curving up", "zurück", "hoch"],
    "⤵️": ["pfeil nach unten rechts", "right arrow curving down", "eingang", "runter"],
    "🔃": ["kreispfeil", "clockwise vertical arrows", "reload", "neu laden", "wiederholen"],
    "🔄": ["gegen uhrzeigersinn", "counterclockwise arrows", "refresh", "aktualisieren"],
    "🔙": ["zurück", "back arrow", "rückwärts", "back"],
    "🔚": ["ende", "end arrow", "end", "schluss"],
    "🔛": ["an", "on! arrow", "einschalten", "on"],
    "🔜": ["bald", "soon arrow", "soon", "demnächst"],
    "🔝": ["top", "top arrow", "oben", "nach oben"],
    "🛐": ["gotteshaus", "place of worship", "religion", "kirche", "beten", "anbetung"],
    "⚛️": ["atom", "atom symbol", "physik", "chemie", "molekül", "wissenschaft"],
    "🕉️": ["om", "om symbol", "hinduismus", "buddhismus", "spirituell", "meditation"],
    "✡️": ["davidstern", "star of david", "judentum", "jewish", "religion", "israel"],
    "☸️": ["dharmarad", "wheel of dharma", "buddhismus", "buddhism", "religion"],
    "☯️": ["yin yang", "yin-yang", "gleichgewicht", "balance", "taoismus", "buddhismus"],
    "✝️": ["kreuz", "latin cross", "christentum", "christianity", "kirche", "religion"],
    "☦️": ["orthodoxes kreuz", "orthodox cross", "christentum", "religion", "orthodox"],
    "☪️": ["halbmond stern", "star and crescent", "islam", "muslimisch", "religion"],
    "☮️": ["frieden", "peace symbol", "frieden", "peace", "hippie", "anti-krieg"],
    "🕎": ["menora", "menorah", "judentum", "jewish", "chanukka", "licht"],
    "🔯": ["sechszackiger stern", "dotted six-pointed star", "judentum", "davidstern", "religion"],
    "🪯": ["khanda", "sikhismus", "sikh", "religion", "schwert"],
    "♈": ["widder", "aries", "sternzeichen", "zodiac", "horoskop", "feuer"],
    "♉": ["stier", "taurus", "sternzeichen", "zodiac", "horoskop", "erde"],
    "♊": ["zwillinge", "gemini", "sternzeichen", "zodiac", "horoskop", "luft"],
    "♋": ["krebs", "cancer", "sternzeichen", "zodiac", "horoskop", "wasser"],
    "♌": ["löwe", "leo", "sternzeichen", "zodiac", "horoskop", "feuer"],
    "♍": ["jungfrau", "virgo", "sternzeichen", "zodiac", "horoskop", "erde"],
    "♎": ["waage", "libra", "sternzeichen", "zodiac", "horoskop", "luft"],
    "♏": ["skorpion", "scorpio", "sternzeichen", "zodiac", "horoskop", "wasser"],
    "♐": ["schütze", "sagittarius", "sternzeichen", "zodiac", "horoskop", "feuer"],
    "♑": ["steinbock", "capricorn", "sternzeichen", "zodiac", "horoskop", "erde"],
    "♒": ["wassermann", "aquarius", "sternzeichen", "zodiac", "horoskop", "luft"],
    "♓": ["fische", "pisces", "sternzeichen", "zodiac", "horoskop", "wasser"],
    "⛎": ["ophiuchus", "schlangenträger", "sternzeichen", "zodiac", "horoskop"],
    "🔀": ["mischen", "shuffle tracks", "shuffle", "zufällig", "random", "musik"],
    "🔁": ["wiederholen", "repeat", "loop", "schleife", "musik", "nochmal"],
    "🔂": ["einmal wiederholen", "repeat single", "repeat one", "loop", "musik"],
    "▶️": ["abspielen", "play", "start", "starten", "musik", "video"],
    "⏩": ["vorspulen", "fast-forward", "schnell", "skip", "musik", "video"],
    "⏭️": ["nächster", "next track", "weiter", "skip", "next", "musik"],
    "⏯️": ["play pause", "play or pause", "toggle", "musik", "video"],
    "◀️": ["zurück", "reverse", "rückwärts", "back", "musik", "video"],
    "⏪": ["zurückspulen", "fast reverse", "schnell zurück", "rewind", "musik"],
    "⏮️": ["letzter", "last track", "vorheriger", "previous", "musik"],
    "🔼": ["aufwärts", "upwards", "hoch", "up", "erhöhen", "pfeil"],
    "⏫": ["schnell aufwärts", "fast up", "hoch", "up", "schnell"],
    "🔽": ["abwärts", "downwards", "runter", "down", "verringern", "pfeil"],
    "⏬": ["schnell abwärts", "fast down", "runter", "down", "schnell"],
    "⏸️": ["pause", "pause button", "stopp", "halten", "musik", "video"],
    "⏹️": ["stopp", "stop button", "beenden", "musik", "video", "stop"],
    "⏺️": ["aufnahme", "record", "aufnehmen", "recording", "rot", "musik"],
    "⏏️": ["auswerfen", "eject", "cd", "dvd", "entfernen", "disc"],
    "🎦": ["kino", "cinema", "film", "movie", "lichtspiele"],
    "🔅": ["dimmen", "dim", "hell dunkel", "helligkeit", "brightness", "leise"],
    "🔆": ["hell", "bright", "helligkeit", "brightness", "licht"],
    "📶": ["signalstärke", "antenna bars", "empfang", "netz", "mobilfunk", "wlan"],
    "🛜": ["wlan", "wireless", "wifi", "internet", "kabellos"],
    "📳": ["vibration", "vibration mode", "vibrieren", "lautlos", "silent", "handy"],
    "📴": ["handy aus", "mobile phone off", "ausschalten", "offline", "kein signal"],
    "♀️": ["weiblich", "female sign", "frau", "woman", "gender", "venus"],
    "♂️": ["männlich", "male sign", "mann", "man", "gender", "mars"],
    "⚧️": ["transgender", "transgender symbol", "gender", "queer", "trans"],
    "✖️": ["multiplizieren", "multiply", "mal", "kreuz", "times", "mathematik"],
    "➕": ["plus", "addition", "addieren", "mehr", "mathematik"],
    "➖": ["minus", "subtraction", "subtrahieren", "weniger", "mathematik"],
    "➗": ["dividieren", "divide", "division", "geteilt", "mathematik"],
    "🟰": ["gleich", "heavy equals sign", "gleich", "equals", "mathematik"],
    "♾️": ["unendlich", "infinity", "endlos", "endless", "mathematik", "ewig"],
    "‼️": ["doppelausrufezeichen", "double exclamation", "wichtig", "wichtig", "achtung"],
    "⁉️": ["ausrufe fragezeichen", "exclamation question", "was", "achtung", "interrobang"],
    "❔": ["weißes fragezeichen", "white question mark", "frage", "unklar"],
    "❕": ["weißes ausrufezeichen", "white exclamation mark", "achtung", "wichtig"],
    "〰️": ["wellenstrich", "wavy dash", "ungefähr", "about", "welle", "approx"],
    "💱": ["währung", "currency exchange", "tauschen", "exchange", "geld", "wechsel"],
    "💲": ["dollar", "heavy dollar sign", "geld", "money", "us", "preis"],
    "⚕️": ["medizin", "medical symbol", "äskulap", "arzt", "gesundheit", "schlange"],
    "⚜️": ["lilie", "fleur-de-lis", "frankreich", "france", "royalty", "wappen"],
    "🔱": ["dreizack", "trident emblem", "neptun", "poseidon", "meer", "japan"],
    "📛": ["namensschild", "name badge", "ausweis", "name", "badge", "tag"],
    "🔰": ["anfänger", "japanese symbol for beginner", "japan", "fahranfänger", "novice"],
    "⭕": ["roter kreis", "hollow red circle", "kreis", "circle", "richtig", "japan"],
    "☑️": ["kontrollkästchen", "check box with check", "erledigt", "haken", "bestätigt"],
    "✔️": ["häkchen", "check mark", "erledigt", "ok", "richtig", "fertig"],
    "❎": ["kreuzknopf", "cross mark button", "nein", "fehler", "x", "falsch"],
    "➰": ["schleife", "curly loop", "schleifen", "dekorativ", "spirale"],
    "➿": ["doppelschleife", "double curly loop", "voicemail", "schleifen"],
    "〽️": ["wechselzeichen", "part alternation mark", "japan", "japanisch", "musik"],
    "✳️": ["achtstrahlig", "eight-spoked asterisk", "stern", "star", "asterisk"],
    "✴️": ["achtspitz", "eight-pointed star", "stern", "star", "dekorativ"],
    "❇️": ["funken", "sparkle", "glitzer", "dekorativ", "glänzend"],
    "🔟": ["zehn", "keycap 10", "10", "nummer", "taste", "zahl"],
    "🔠": ["großbuchstaben", "input latin uppercase", "abc", "großschrift", "buchstaben"],
    "🔡": ["kleinbuchstaben", "input latin lowercase", "abc", "kleinschrift", "buchstaben"],
    "🔢": ["zahlen", "input numbers", "123", "nummern", "ziffern"],
    "🔣": ["symbole", "input symbols", "sonderzeichen", "zeichen", "special"],
    "🔤": ["buchstaben", "input latin letters", "abc", "alphabet", "schrift"],
    "🅰️": ["a knopf", "a button", "blutgruppe", "blood type", "buchstabe"],
    "🆎": ["ab knopf", "ab button", "blutgruppe", "blood type"],
    "🅱️": ["b knopf", "b button", "blutgruppe", "blood type", "buchstabe"],
    "🆑": ["cl knopf", "cl button", "löschen", "clear", "cancel"],
    "🆒": ["cool knopf", "cool button", "cool", "geil", "super"],
    "🆓": ["frei knopf", "free button", "kostenlos", "gratis", "free"],
    "ℹ️": ["information", "info", "hilfe", "hinweis", "auskunft"],
    "🆔": ["ausweis", "id button", "identität", "identity", "nummer"],
    "Ⓜ️": ["m im kreis", "circled m", "metro", "ubahn", "m"],
    "🆕": ["neu knopf", "new button", "neu", "new", "frisch"],
    "🆖": ["ng knopf", "ng button", "nicht gut", "not good", "fehler"],
    "🅾️": ["o knopf", "o button", "blutgruppe", "blood type", "buchstabe"],
    "🆗": ["ok knopf", "ok button", "okay", "gut", "bestätigt"],
    "🅿️": ["p knopf", "p button", "parken", "parking", "parkplatz"],
    "🆘": ["sos knopf", "sos button", "notfall", "hilfe", "help", "notstand"],
    "🆙": ["up knopf", "up! button", "aufwärts", "hoch", "besser"],
    "🆚": ["vs knopf", "vs button", "versus", "gegen", "vergleich"],
    "🈁": ["japanisch hier", "japanese here", "japan", "ここ", "koko"],
    "🈂️": ["service japanisch", "japanese service charge", "japan", "サ", "service"],
    "🈷️": ["monatlich japanisch", "japanese monthly amount", "japan", "月", "monat"],
    "🈶": ["kostenpflichtig japanisch", "japanese not free of charge", "japan", "有", "bezahlen"],
    "🈯": ["reserviert japanisch", "japanese reserved", "japan", "指", "reservierung"],
    "🉐": ["schnäppchen japanisch", "japanese bargain", "japan", "得", "angebot"],
    "🈹": ["rabatt japanisch", "japanese discount", "japan", "割", "rabatt"],
    "🈚": ["kostenlos japanisch", "japanese free of charge", "japan", "無", "gratis"],
    "🈲": ["verboten japanisch", "japanese prohibited", "japan", "禁", "verboten"],
    "🉑": ["akzeptiert japanisch", "japanese acceptable", "japan", "可", "akzeptiert"],
    "🈸": ["antrag japanisch", "japanese application", "japan", "申", "antrag"],
    "🈴": ["bestanden japanisch", "japanese passing grade", "japan", "合", "bestanden"],
    "🈳": ["frei japanisch", "japanese vacancy", "japan", "空", "frei"],
    "㊗️": ["glückwunsch japanisch", "japanese congratulations", "japan", "祝", "glückwunsch"],
    "㊙️": ["geheim japanisch", "japanese secret", "japan", "秘", "geheim"],
    "🈺": ["geöffnet japanisch", "japanese open for business", "japan", "営", "geöffnet"],
    "🈵": ["kein platz japanisch", "japanese no vacancy", "japan", "満", "ausgebucht"],
    "🟤": ["brauner kreis", "brown circle", "braun", "brown", "kreis", "circle"],
    "🟥": ["rotes quadrat", "red square", "rot", "red", "quadrat", "square"],
    "🟧": ["oranges quadrat", "orange square", "orange", "quadrat", "square"],
    "🟨": ["gelbes quadrat", "yellow square", "gelb", "yellow", "quadrat", "square"],
    "🟩": ["grünes quadrat", "green square", "grün", "green", "quadrat", "square"],
    "🟦": ["blaues quadrat", "blue square", "blau", "blue", "quadrat", "square"],
    "🟪": ["lila quadrat", "purple square", "lila", "purple", "quadrat", "square"],
    "🟫": ["braunes quadrat", "brown square", "braun", "brown", "quadrat", "square"],
    "⬛": ["schwarzes großes quadrat", "black large square", "schwarz", "black", "quadrat"],
    "⬜": ["weißes großes quadrat", "white large square", "weiß", "white", "quadrat"],
    "◼️": ["schwarzes quadrat", "black medium square", "schwarz", "black", "quadrat"],
    "◻️": ["weißes quadrat", "white medium square", "weiß", "white", "quadrat"],
    "◾": ["schwarzes kleines quadrat", "black medium-small square", "schwarz", "quadrat"],
    "◽": ["weißes kleines quadrat", "white medium-small square", "weiß", "quadrat"],
    "▪️": ["schwarzes winziges quadrat", "black small square", "schwarz", "quadrat", "punkt"],
    "▫️": ["weißes winziges quadrat", "white small square", "weiß", "quadrat", "punkt"],
    "🔶": ["große orange raute", "large orange diamond", "orange", "raute", "diamond"],
    "🔷": ["große blaue raute", "large blue diamond", "blau", "blue", "raute", "diamond"],
    "🔸": ["kleine orange raute", "small orange diamond", "orange", "raute", "diamond"],
    "🔹": ["kleine blaue raute", "small blue diamond", "blau", "blue", "raute", "diamond"],
    "🔺": ["rotes dreieck oben", "red triangle pointed up", "rot", "dreieck", "triangle"],
    "🔻": ["rotes dreieck unten", "red triangle pointed down", "rot", "dreieck", "triangle"],
    "💠": ["raute mit punkt", "diamond with a dot", "blau", "raute", "diamond", "dekorativ"],
    "🔘": ["radio button", "kreis", "auswahl", "option", "radio"],
    "🔳": ["weißer quadratknopf", "white square button", "weiß", "quadrat", "taste"],
    "🔲": ["schwarzer quadratknopf", "black square button", "schwarz", "quadrat", "taste"],

    # Flags — deutsche Bezeichnungen
    "🇩🇪": ["deutschland", "germany", "deutsch", "german", "brd"],
    "🇦🇹": ["österreich", "austria"],
    "🇨🇭": ["schweiz", "switzerland"],
    "🇺🇸": ["usa", "amerika", "america", "vereinigte staaten"],
    "🇬🇧": ["england", "großbritannien", "uk", "vereinigtes königreich", "british"],
    "🇫🇷": ["frankreich", "france", "französisch"],
    "🇮🇹": ["italien", "italy"],
    "🇪🇸": ["spanien", "spain"],
    "🇵🇹": ["portugal"],
    "🇳🇱": ["niederlande", "netherlands", "holland"],
    "🇧🇪": ["belgien", "belgium"],
    "🇩🇰": ["dänemark", "denmark"],
    "🇸🇪": ["schweden", "sweden"],
    "🇳🇴": ["norwegen", "norway"],
    "🇫🇮": ["finnland", "finland"],
    "🇮🇪": ["irland", "ireland"],
    "🇵🇱": ["polen", "poland"],
    "🇨🇿": ["tschechien", "czechia", "czech"],
    "🇭🇺": ["ungarn", "hungary"],
    "🇷🇴": ["rumänien", "romania"],
    "🇭🇷": ["kroatien", "croatia"],
    "🇬🇷": ["griechenland", "greece"],
    "🇹🇷": ["türkei", "turkey"],
    "🇷🇺": ["russland", "russia"],
    "🇺🇦": ["ukraine"],
    "🇯🇵": ["japan", "japanisch"],
    "🇨🇳": ["china", "chinesisch"],
    "🇰🇷": ["südkorea", "south korea", "korea"],
    "🇮🇳": ["indien", "india"],
    "🇧🇷": ["brasilien", "brazil"],
    "🇲🇽": ["mexiko", "mexico"],
    "🇨🇦": ["kanada", "canada"],
    "🇦🇺": ["australien", "australia"],
    "🇪🇺": ["eu", "europa", "europe", "europäische union"],
    "🏳️": ["weiße flagge", "white flag", "surrender", "kapitulation", "waffenstillstand"],
    "🏴": ["schwarze flagge", "black flag", "anarchie", "pirat", "dunkel"],
    "🏁": ["zielflagge", "chequered flag", "rennen", "race", "ziel", "finish", "motorsport"],
    "🚩": ["dreieckige flagge", "triangular flag", "warnung", "markierung", "checkpoint"],
    "🏳️‍🌈": ["regenbogenflagge", "rainbow flag", "lgbt", "pride", "queer", "gay", "toleranz"],
    "🏳️‍⚧️": ["transgender flagge", "transgender flag", "trans", "pride", "queer"],
    "🏴‍☠️": ["piratenflagge", "pirate flag", "jolly roger", "pirat", "totenkopf", "piracy"],
    "🇱🇺": ["luxemburg", "luxembourg", "luxemburgisch", "hauptstadt luxemburg-stadt"],
    "🇮🇸": ["island", "iceland", "isländisch", "reykjavik", "nordeuropa"],
    "🇧🇬": ["bulgarien", "bulgaria", "bulgarisch", "sofia", "osteuropa"],
    "🇸🇮": ["slowenien", "slovenia", "slowenisch", "laibach", "ljubljana", "osteuropa"],
    "🇸🇰": ["slowakei", "slovakia", "slowakisch", "bratislava", "pressburg", "osteuropa"],
    "🇳🇿": ["neuseeland", "new zealand", "neuseeländisch", "wellington", "auckland", "ozeanien"],
    "🇿🇦": ["südafrika", "south africa", "südafrikanisch", "pretoria", "kapstadt", "johannesburg"],
    "🇪🇬": ["ägypten", "egypt", "ägyptisch", "kairo", "cairo", "nordafrika", "pyramiden"],
    "🇳🇬": ["nigeria", "nigerianisch", "abuja", "lagos", "westafrika"],
    "🇰🇪": ["kenia", "kenya", "kenianisch", "nairobi", "ostafrika"],
    "🇦🇷": ["argentinien", "argentina", "argentinisch", "buenos aires", "südamerika"],
    "🇨🇱": ["chile", "chilenisch", "santiago", "südamerika"],
    "🇨🇴": ["kolumbien", "colombia", "kolumbianisch", "bogotá", "südamerika"],
    "🇵🇪": ["peru", "peruanisch", "lima", "südamerika", "machu picchu", "anden"],
    "🇻🇪": ["venezuela", "venezolanisch", "caracas", "südamerika"],
    "🇸🇦": ["saudi arabien", "saudi arabia", "saudi-arabisch", "riad", "riyadh", "naher osten"],
    "🇦🇪": ["vereinigte arabische emirate", "united arab emirates", "uae", "dubai", "abu dhabi"],
    "🇮🇱": ["israel", "israelisch", "jerusalem", "tel aviv", "naher osten"],
    "🇹🇭": ["thailand", "thailändisch", "bangkok", "südostasien"],
    "🇻🇳": ["vietnam", "vietnamesisch", "hanoi", "ho chi minh", "südostasien"],
    "🇮🇩": ["indonesien", "indonesia", "indonesisch", "jakarta", "südostasien"],
    "🇲🇾": ["malaysia", "malaysisch", "kuala lumpur", "südostasien"],
    "🇸🇬": ["singapur", "singapore", "singapurisch", "stadtsstaat", "südostasien"],
    "🇵🇭": ["philippinen", "philippines", "philippinisch", "manila", "südostasien"],
    "🇹🇼": ["taiwan", "taiwanisch", "taipeh", "taipei", "ostasien"],
    "🇭🇰": ["hongkong", "hong kong", "hongkonger", "china", "sonderverwaltungszone"],
    "🇵🇰": ["pakistan", "pakistanisch", "islamabad", "karachi", "südasien"],
    "🇧🇩": ["bangladesch", "bangladesh", "bangladeschisch", "dhaka", "südasien"],
    "🇱🇰": ["sri lanka", "sri-lankisch", "colombo", "südasien"],
    "🇳🇵": ["nepal", "nepalesisch", "kathmandu", "himalaya", "südasien"],
    "🇲🇲": ["myanmar", "burma", "myanmarisch", "naypyidaw", "yangon", "südostasien"],
    "🇰🇭": ["kambodscha", "cambodia", "kambodschanisch", "phnom penh", "südostasien"],
    "🇱🇦": ["laos", "laotisch", "vientiane", "südostasien"],
    "🇲🇳": ["mongolei", "mongolia", "mongolisch", "ulaanbaatar", "zentralasien"],
    "🇰🇵": ["nordkorea", "north korea", "nordkoreanisch", "pjöngjang", "pyongyang", "ostasien"],
    "🇦🇫": ["afghanistan", "afghanisch", "kabul", "zentralasien"],
    "🇮🇶": ["irak", "iraq", "irakisch", "bagdad", "naher osten"],
    "🇮🇷": ["iran", "iranisch", "teheran", "persien", "naher osten"],
    "🇸🇾": ["syrien", "syria", "syrisch", "damaskus", "naher osten"],
    "🇱🇧": ["libanon", "lebanon", "libanesisch", "beirut", "naher osten"],
    "🇯🇴": ["jordanien", "jordan", "jordanisch", "amman", "naher osten"],
    "🇶🇦": ["katar", "qatar", "katarisch", "doha", "naher osten"],
    "🇰🇼": ["kuwait", "kuwaitisch", "kuwait-stadt", "kuwait city", "naher osten"],
    "🇧🇭": ["bahrain", "bahrainisch", "manama", "naher osten"],
    "🇴🇲": ["oman", "omanisch", "maskat", "muscat", "naher osten"],
    "🇾🇪": ["jemen", "yemen", "jemenitisch", "sanaa", "naher osten"],
    "🇨🇺": ["kuba", "cuba", "kubanisch", "havanna", "havana", "karibik"],
    "🇯🇲": ["jamaika", "jamaica", "jamaiканisch", "kingston", "karibik"],
    "🇭🇹": ["haiti", "haitianisch", "port-au-prince", "karibik"],
    "🇩🇴": ["dominikanische republik", "dominican republic", "santo domingo", "karibik"],
    "🇵🇦": ["panama", "panamaisch", "panama-stadt", "panama city", "mittelamerika"],
    "🇨🇷": ["costa rica", "costa-ricanisch", "san josé", "mittelamerika"],
    "🇪🇪": ["estland", "estonia", "estnisch", "tallinn", "nordeuropa", "baltikum"],
    "🇱🇻": ["lettland", "latvia", "lettisch", "riga", "nordeuropa", "baltikum"],
    "🇱🇹": ["litauen", "lithuania", "litauisch", "vilnius", "nordeuropa", "baltikum"],
    "🇷🇸": ["serbien", "serbia", "serbisch", "belgrad", "belgrade", "osteuropa"],
    "🇲🇪": ["montenegro", "montenegrinisch", "podgorica", "osteuropa", "balkan"],
    "🇲🇰": ["nordmazedonien", "north macedonia", "mazedonisch", "skopje", "balkan"],
    "🇦🇱": ["albanien", "albania", "albanisch", "tirana", "balkan"],
    "🇧🇦": ["bosnien herzegowina", "bosnia herzegovina", "bosnisch", "sarajevo", "balkan"],
    "🇲🇹": ["malta", "maltesisch", "valletta", "mittelmeer"],
    "🇨🇾": ["zypern", "cyprus", "zyprisch", "nikosia", "nicosia", "mittelmeer"],
    "🇬🇪": ["georgien", "georgia", "georgisch", "tiflis", "tbilisi", "kaukasus"],
    "🇦🇲": ["armenien", "armenia", "armenisch", "jerewan", "yerevan", "kaukasus"],
    "🇦🇿": ["aserbaidschan", "azerbaijan", "aserbaidschanisch", "baku", "kaukasus"],
    "🇰🇿": ["kasachstan", "kazakhstan", "kasachisch", "astana", "zentralasien"],
    "🇺🇿": ["usbekistan", "uzbekistan", "usbekisch", "taschkent", "tashkent", "zentralasien"],
    "🇪🇹": ["äthiopien", "ethiopia", "äthiopisch", "addis abeba", "ostafrika"],
    "🇹🇿": ["tansania", "tanzania", "tansanisch", "dodoma", "dar es salaam", "ostafrika"],
    "🇬🇭": ["ghana", "ghanaisch", "accra", "westafrika"],
    "🇸🇳": ["senegal", "senegalesisch", "dakar", "westafrika"],
    "🇲🇦": ["marokko", "morocco", "marokkanisch", "rabat", "casablanca", "nordafrika"],
    "🇹🇳": ["tunesien", "tunisia", "tunesisch", "tunis", "nordafrika"],
    "🇩🇿": ["algerien", "algeria", "algerisch", "algier", "algiers", "nordafrika"],
    "🇱🇾": ["libyen", "libya", "libysch", "tripolis", "tripoli", "nordafrika"],
    "🇪🇨": ["ecuador", "ecuadorianisch", "quito", "südamerika"],
    "🇧🇴": ["bolivien", "bolivia", "bolivianisch", "sucre", "la paz", "südamerika"],
    "🇵🇾": ["paraguay", "paraguayisch", "asunción", "südamerika"],
    "🇺🇾": ["uruguay", "uruguayisch", "montevideo", "südamerika"],
    "🇬🇹": ["guatemala", "guatemaltekisch", "guatemala-stadt", "mittelamerika"],
    "🇭🇳": ["honduras", "honduranisch", "tegucigalpa", "mittelamerika"],
    "🇳🇮": ["nicaragua", "nicaraguanisch", "managua", "mittelamerika"],
    "🇸🇻": ["el salvador", "salvadorianisch", "san salvador", "mittelamerika"],
    "🇺🇳": ["vereinte nationen", "united nations", "un", "uno", "international", "weltorganisation"],
}
