"""
Search tags for emojis — includes German terms, synonyms, and common aliases.
Maps emoji character to a list of additional search terms.
"""

SEARCH_TAGS = {
    # Smileys
    "😀": ["grinsen", "lachen", "happy", "smile", "grin", "freude"],
    "😃": ["grinsen", "lachen", "happy", "smile", "freude", "fröhlich"],
    "😄": ["grinsen", "lachen", "happy", "smile", "freude", "fröhlich"],
    "😁": ["grinsen", "lachen", "strahlen", "beam", "happy"],
    "😆": ["lachen", "haha", "xD", "laugh", "lustig"],
    "😅": ["schwitzen", "sweat", "nervös", "nervous", "lachen"],
    "🤣": ["rofl", "lol", "totlachen", "laugh", "lustig", "witzig"],
    "😂": ["lol", "lachen", "tränen", "tears", "laugh", "lustig", "witzig", "haha"],
    "🙂": ["lächeln", "smile", "leicht", "slight"],
    "🙃": ["verkehrt", "upside", "sarkasmus", "ironie", "sarcasm"],
    "😉": ["zwinkern", "wink", "augenzwinkern"],
    "😊": ["lächeln", "smile", "verlegen", "shy", "blush", "süß"],
    "😇": ["engel", "angel", "heilig", "holy", "brav"],
    "🥰": ["verliebt", "love", "herzen", "hearts", "liebe", "schwärmen"],
    "😍": ["verliebt", "love", "herzaugen", "heart eyes", "liebe"],
    "🤩": ["star", "stern", "begeistert", "wow", "amazing", "toll"],
    "😘": ["kuss", "kiss", "bussi", "küsschen", "herz"],
    "😗": ["kuss", "kiss", "bussi"],
    "😚": ["kuss", "kiss", "bussi"],
    "😙": ["kuss", "kiss", "bussi"],
    "🥲": ["traurig", "lächeln", "träne", "sad", "smile", "tear"],
    "😋": ["lecker", "yummy", "essen", "food", "delicious", "mmh"],
    "😛": ["zunge", "tongue", "frech", "raus"],
    "😜": ["zunge", "zwinkern", "frech", "wink", "tongue", "crazy"],
    "🤪": ["verrückt", "crazy", "wild", "zany", "wahnsinn"],
    "😝": ["zunge", "tongue", "bäh", "frech"],
    "🤑": ["geld", "money", "reich", "dollar", "cash"],
    "🤗": ["umarmen", "hug", "umarmung", "knuddeln"],
    "🤭": ["kichern", "giggle", "oops", "ups", "huch"],
    "🤫": ["pst", "leise", "shh", "quiet", "still", "geheim", "secret"],
    "🤔": ["denken", "think", "hmm", "überlegen", "nachdenken", "grübeln"],
    "🫡": ["salut", "salute", "jawohl", "respekt"],
    "🤐": ["mund zu", "zip", "still", "quiet", "reißverschluss"],
    "🤨": ["skeptisch", "suspicious", "hmm", "zweifel", "doubt"],
    "😐": ["neutral", "meh", "gleichgültig"],
    "😑": ["genervt", "annoyed", "ausdruckslos", "meh"],
    "😶": ["still", "silent", "speechless", "sprachlos", "kein kommentar"],
    "😏": ["grinsen", "smirk", "frech", "schlau", "hehe"],
    "😒": ["genervt", "unamused", "gelangweilt", "bored", "meh"],
    "🙄": ["augenrollen", "eye roll", "genervt", "nervig", "bitte"],
    "😬": ["grimasse", "awkward", "peinlich", "oops", "yikes"],
    "🤥": ["lügen", "lie", "pinocchio", "lügner"],
    "😌": ["erleichtert", "relieved", "entspannt", "relaxed", "frieden"],
    "😔": ["nachdenklich", "traurig", "sad", "down"],
    "😪": ["müde", "sleepy", "tired", "schläfrig"],
    "🤤": ["sabbern", "drool", "lecker", "hunger"],
    "😴": ["schlafen", "sleep", "müde", "tired", "zzz", "pennen"],
    "😷": ["maske", "mask", "krank", "sick", "corona", "covid"],
    "🤒": ["krank", "sick", "fieber", "fever", "thermometer"],
    "🤕": ["verletzt", "hurt", "kopf", "bandage", "aua", "autsch"],
    "🤢": ["übel", "nausea", "kotzen", "sick", "grün"],
    "🤮": ["kotzen", "vomit", "übergeben", "sick", "bah"],
    "🥵": ["heiß", "hot", "schwitzen", "hitze", "warm"],
    "🥶": ["kalt", "cold", "frieren", "frost", "eisig"],
    "🥴": ["betrunken", "drunk", "benommen", "dizzy", "woozy"],
    "😵": ["schwindel", "dizzy", "ko", "ohnmacht"],
    "🤯": ["explodieren", "mind blown", "wow", "krass", "wahnsinn"],
    "🤠": ["cowboy", "western", "yeehaw"],
    "🥳": ["party", "feier", "geburtstag", "birthday", "feiern"],
    "🥸": ["verkleidet", "disguise", "inkognito", "tarnung"],
    "😎": ["cool", "sonnenbrille", "sunglasses", "lässig"],
    "🤓": ["nerd", "streber", "brille", "schlau", "geek"],
    "🧐": ["monokel", "schick", "fancy", "prüfen", "inspect"],
    "😕": ["verwirrt", "confused", "unsicher", "hä"],
    "😟": ["besorgt", "worried", "sorge"],
    "🙁": ["traurig", "sad", "frown", "enttäuscht"],
    "😮": ["oh", "überrascht", "surprised", "wow"],
    "😯": ["überrascht", "surprised", "oh"],
    "😲": ["erstaunt", "astonished", "schock", "shocked", "wow"],
    "😳": ["peinlich", "embarrassed", "rot", "blush", "flush"],
    "🥺": ["bitte", "please", "flehen", "süß", "cute", "puppy"],
    "🥹": ["rührung", "tears", "emotional", "gerührt"],
    "😨": ["angst", "fear", "scared", "erschrocken"],
    "😰": ["angst", "schwitzen", "anxious", "nervous", "stress"],
    "😥": ["traurig", "erleichtert", "sad"],
    "😢": ["weinen", "cry", "traurig", "sad", "träne"],
    "😭": ["heulen", "weinen", "cry", "traurig", "sad", "schluchzen"],
    "😱": ["schreien", "scream", "horror", "schock", "angst", "panik"],
    "😖": ["frustration", "verzweifelt", "ugh"],
    "😣": ["anstrengung", "persevere", "durchhalten"],
    "😞": ["enttäuscht", "disappointed", "traurig", "sad"],
    "😓": ["schwitzen", "stress", "erschöpft"],
    "😩": ["erschöpft", "weary", "tired", "müde", "fertig"],
    "😫": ["müde", "tired", "erschöpft", "fertig"],
    "🥱": ["gähnen", "yawn", "müde", "langweilig", "boring"],
    "😤": ["wütend", "angry", "dampf", "steam", "sauer"],
    "😡": ["wütend", "angry", "sauer", "zorn", "rage", "mad"],
    "😠": ["wütend", "angry", "sauer", "böse", "mad"],
    "🤬": ["fluchen", "swear", "schimpfen", "wütend", "angry"],
    "😈": ["teufel", "devil", "böse", "evil", "frech"],
    "👿": ["teufel", "devil", "böse", "evil", "wütend"],
    "💀": ["tot", "dead", "skull", "schädel", "totenkopf", "rip"],
    "☠️": ["tot", "dead", "gift", "poison", "gefahr", "danger"],
    "💩": ["kacke", "poop", "shit", "mist", "scheiße"],
    "🤡": ["clown", "lustig", "witzig", "zirkus"],
    "👹": ["dämon", "demon", "monster", "ungeheuer"],
    "👺": ["kobold", "goblin", "maske"],
    "👻": ["geist", "ghost", "spuk", "halloween", "boo"],
    "👽": ["alien", "außerirdisch", "ufo"],
    "👾": ["alien", "monster", "videospiel", "game", "pixel"],
    "🤖": ["roboter", "robot", "maschine", "ki", "ai"],
    "😺": ["katze", "cat", "lachen", "grinsen"],
    "😸": ["katze", "cat", "lachen"],
    "😹": ["katze", "cat", "lachen", "freude"],
    "😻": ["katze", "cat", "verliebt", "herz"],
    "😼": ["katze", "cat", "grinsen"],
    "😽": ["katze", "cat", "kuss"],
    "🙀": ["katze", "cat", "schock", "oh nein"],
    "😿": ["katze", "cat", "traurig", "weinen"],
    "😾": ["katze", "cat", "wütend", "sauer"],
    "🫶": ["herzhände", "heart hands", "liebe", "love", "danke"],
    "❤️": ["herz", "heart", "liebe", "love", "rot", "red"],
    "🧡": ["herz", "heart", "orange", "liebe"],
    "💛": ["herz", "heart", "gelb", "yellow", "liebe"],
    "💚": ["herz", "heart", "grün", "green", "liebe"],
    "💙": ["herz", "heart", "blau", "blue", "liebe"],
    "💜": ["herz", "heart", "lila", "purple", "liebe"],
    "🖤": ["herz", "heart", "schwarz", "black", "trauer"],
    "🤍": ["herz", "heart", "weiß", "white"],
    "🤎": ["herz", "heart", "braun", "brown"],
    "💔": ["herz", "gebrochen", "broken", "traurig", "herzschmerz", "liebeskummer"],
    "❤️‍🔥": ["herz", "feuer", "fire", "leidenschaft", "passion"],
    "❤️‍🩹": ["herz", "heilung", "healing", "pflaster"],
    "💕": ["herzen", "hearts", "liebe", "love"],
    "💞": ["herzen", "hearts", "liebe", "love"],
    "💓": ["herz", "heart", "schlagen", "beat"],
    "💗": ["herz", "heart", "wachsen", "growing"],
    "💖": ["herz", "heart", "funkeln", "sparkle"],
    "💘": ["herz", "heart", "amor", "pfeil", "arrow", "verliebt"],
    "💝": ["herz", "heart", "geschenk", "gift", "schleife"],
    "💟": ["herz", "heart", "dekoration"],
    "🩷": ["herz", "heart", "pink", "rosa"],
    "🩵": ["herz", "heart", "hellblau", "light blue"],
    "🩶": ["herz", "heart", "grau", "grey"],
    "💯": ["hundert", "hundred", "perfekt", "perfect", "100", "top"],
    "💢": ["wut", "anger", "ärger"],
    "💥": ["explosion", "boom", "crash", "knall", "bumm"],
    "💫": ["schwindel", "stern", "star", "dizzy"],
    "💦": ["schweiß", "tropfen", "sweat", "wasser", "water"],
    "💨": ["wind", "schnell", "fast", "pups", "fart", "weg"],
    "💬": ["sprechblase", "speech", "chat", "nachricht", "message"],
    "💭": ["denken", "thought", "gedanke"],
    "💤": ["schlafen", "sleep", "müde", "zzz"],

    # People & Body
    "👋": ["winken", "wave", "hallo", "hello", "hi", "tschüss", "bye"],
    "🤚": ["hand", "stop", "halt"],
    "🖐️": ["hand", "finger", "fünf", "five", "high five"],
    "✋": ["hand", "stop", "halt", "high five"],
    "🖖": ["vulkanier", "spock", "star trek", "live long"],
    "👌": ["ok", "okay", "gut", "good", "perfekt", "perfect", "nice"],
    "🤌": ["italian", "italienisch", "was willst du", "chef kiss"],
    "🤏": ["wenig", "little", "klein", "small", "bisschen", "tiny"],
    "✌️": ["victory", "sieg", "frieden", "peace", "zwei", "two"],
    "🤞": ["daumen drücken", "fingers crossed", "glück", "luck", "hoffen"],
    "🤟": ["liebe", "love", "rock"],
    "🤘": ["rock", "metal", "party", "teufel"],
    "🤙": ["anrufen", "call", "hang loose", "shaka", "ruf an"],
    "👈": ["links", "left", "zeigen", "point"],
    "👉": ["rechts", "right", "zeigen", "point"],
    "👆": ["oben", "up", "zeigen", "point"],
    "🖕": ["mittelfinger", "fuck", "fick dich"],
    "👇": ["unten", "down", "zeigen", "point"],
    "☝️": ["eins", "one", "oben", "achtung", "attention"],
    "🫵": ["du", "you", "zeigen", "point"],
    "👍": ["daumen hoch", "thumbs up", "gut", "good", "ja", "yes", "like", "top", "ok"],
    "👎": ["daumen runter", "thumbs down", "schlecht", "bad", "nein", "no", "dislike"],
    "✊": ["faust", "fist", "kraft", "power", "stark", "strong"],
    "👊": ["faust", "fist", "schlag", "punch", "bro"],
    "🤛": ["faust", "fist", "links"],
    "🤜": ["faust", "fist", "rechts"],
    "👏": ["klatschen", "clap", "applaus", "bravo", "applause"],
    "🙌": ["hände hoch", "celebration", "feier", "jubel", "hooray", "yay"],
    "👐": ["hände", "hands", "offen", "open"],
    "🤲": ["hände", "beten", "bitte", "geben"],
    "🤝": ["handschlag", "handshake", "deal", "abmachung", "vereinbarung"],
    "🙏": ["beten", "pray", "bitte", "please", "danke", "thanks", "namaste"],
    "✍️": ["schreiben", "write", "unterschrift"],
    "💅": ["nagellack", "nail", "schick", "fancy", "slay"],
    "🤳": ["selfie", "foto", "photo"],
    "💪": ["stark", "strong", "bizeps", "muscle", "kraft", "power", "gym", "sport"],
    "👀": ["augen", "eyes", "gucken", "schauen", "look", "see"],
    "👁️": ["auge", "eye", "sehen", "see"],
    "👅": ["zunge", "tongue", "lecken"],
    "👄": ["mund", "mouth", "lippen", "lips", "kuss"],
    "🫦": ["beißen", "bite", "lippe", "lip", "nervös"],
    "👶": ["baby", "kind", "child", "säugling"],
    "👦": ["junge", "boy", "kind"],
    "👧": ["mädchen", "girl", "kind"],
    "👨": ["mann", "man", "herr", "typ", "kerl", "guy"],
    "👩": ["frau", "woman", "dame", "lady"],
    "👴": ["opa", "grandpa", "alter mann", "old man", "rentner"],
    "👵": ["oma", "grandma", "alte frau", "old woman", "rentnerin"],
    "🤦": ["facepalm", "kopf schlagen", "ach nee", "oh mann", "doh"],
    "🤷": ["keine ahnung", "shrug", "weiß nicht", "egal", "idk", "dunno"],
    "👮": ["polizei", "police", "cop", "polizist"],
    "🕵️": ["detektiv", "detective", "spion", "spy", "ermittler"],
    "💂": ["wache", "guard", "soldat"],
    "🥷": ["ninja", "kämpfer", "shinobi"],
    "👷": ["bauarbeiter", "construction", "baustelle", "helm"],
    "🤴": ["prinz", "prince", "könig"],
    "👸": ["prinzessin", "princess", "königin"],
    "🎅": ["weihnachtsmann", "santa", "weihnachten", "christmas", "nikolaus"],
    "🤶": ["weihnachtsfrau", "mrs claus", "weihnachten"],
    "🦸": ["superheld", "superhero", "held", "hero"],
    "🦹": ["superschurke", "villain", "böse"],
    "🧙": ["zauberer", "mage", "wizard", "magie", "magic"],
    "🧚": ["fee", "fairy", "elfe"],
    "🧛": ["vampir", "vampire", "dracula"],
    "🧜": ["meerjungfrau", "mermaid", "merman"],
    "🧝": ["elfe", "elf"],
    "🧟": ["zombie", "untot", "undead"],
    "💃": ["tanzen", "dance", "frau", "salsa", "tanz"],
    "🕺": ["tanzen", "dance", "mann", "disco", "tanz"],
    "🏃": ["rennen", "run", "joggen", "laufen", "sprint"],
    "🚶": ["gehen", "walk", "spazieren", "laufen"],
    "🧍": ["stehen", "stand", "person"],
    "🧎": ["knien", "kneel"],
    "💏": ["kuss", "kiss", "pärchen", "couple"],
    "💑": ["pärchen", "couple", "liebe", "love"],
    "👪": ["familie", "family", "eltern", "kinder"],
    "🫂": ["umarmung", "hug", "umarmen", "trost"],
    "👣": ["fußabdruck", "footprint", "füße", "feet", "schritte"],

    # Animals & Nature
    "🐵": ["affe", "monkey", "ape"],
    "🐒": ["affe", "monkey", "ape"],
    "🦍": ["gorilla", "affe", "ape"],
    "🦧": ["orang utan", "affe", "ape"],
    "🐶": ["hund", "dog", "welpe", "puppy", "wuff", "wau"],
    "🐕": ["hund", "dog"],
    "🐩": ["pudel", "poodle", "hund", "dog"],
    "🐺": ["wolf", "heulen", "howl"],
    "🦊": ["fuchs", "fox", "schlau"],
    "🦝": ["waschbär", "raccoon"],
    "🐱": ["katze", "cat", "mieze", "miau", "kitty"],
    "🐈": ["katze", "cat"],
    "🐈‍⬛": ["katze", "cat", "schwarz", "black"],
    "🦁": ["löwe", "lion", "könig"],
    "🐯": ["tiger"],
    "🐅": ["tiger"],
    "🐆": ["leopard", "gepard", "cheetah"],
    "🐴": ["pferd", "horse", "pony", "ross"],
    "🐎": ["pferd", "horse", "rennen", "race", "reiten"],
    "🦄": ["einhorn", "unicorn", "magisch", "magic"],
    "🦓": ["zebra"],
    "🦌": ["hirsch", "deer", "reh", "bambi"],
    "🐮": ["kuh", "cow", "muh"],
    "🐄": ["kuh", "cow", "milch"],
    "🐷": ["schwein", "pig", "sau", "oink"],
    "🐖": ["schwein", "pig"],
    "🐗": ["wildschwein", "boar"],
    "🐏": ["schaf", "sheep", "widder", "ram"],
    "🐑": ["schaf", "sheep", "lamm", "lamb", "wolle"],
    "🐐": ["ziege", "goat"],
    "🐪": ["kamel", "camel", "wüste", "desert"],
    "🐫": ["kamel", "camel", "wüste"],
    "🦒": ["giraffe"],
    "🐘": ["elefant", "elephant"],
    "🦏": ["nashorn", "rhino"],
    "🦛": ["nilpferd", "hippo", "flusspferd"],
    "🐭": ["maus", "mouse"],
    "🐁": ["maus", "mouse"],
    "🐀": ["ratte", "rat"],
    "🐹": ["hamster"],
    "🐰": ["hase", "rabbit", "kaninchen", "bunny", "ostern", "easter"],
    "🐇": ["hase", "rabbit", "kaninchen"],
    "🐿️": ["eichhörnchen", "chipmunk", "squirrel"],
    "🦔": ["igel", "hedgehog"],
    "🦇": ["fledermaus", "bat", "batman", "halloween"],
    "🐻": ["bär", "bear", "teddy"],
    "🐻‍❄️": ["eisbär", "polar bear", "arktis"],
    "🐨": ["koala"],
    "🐼": ["panda", "bär"],
    "🦥": ["faultier", "sloth", "faul", "lazy"],
    "🦦": ["otter"],
    "🦨": ["stinktier", "skunk"],
    "🦘": ["känguru", "kangaroo"],
    "🐾": ["pfote", "paw", "tatze", "tier", "animal"],
    "🦃": ["truthahn", "turkey", "thanksgiving"],
    "🐔": ["huhn", "chicken", "henne", "hen"],
    "🐓": ["hahn", "rooster"],
    "🐣": ["küken", "chick", "schlüpfen", "hatch"],
    "🐤": ["küken", "chick", "baby"],
    "🐥": ["küken", "chick"],
    "🐦": ["vogel", "bird"],
    "🐧": ["pinguin", "penguin"],
    "🕊️": ["taube", "dove", "frieden", "peace"],
    "🦅": ["adler", "eagle"],
    "🦆": ["ente", "duck", "quak"],
    "🦢": ["schwan", "swan"],
    "🦉": ["eule", "owl", "uhu"],
    "🦩": ["flamingo"],
    "🦚": ["pfau", "peacock"],
    "🦜": ["papagei", "parrot"],
    "🪿": ["gans", "goose"],
    "🐸": ["frosch", "frog", "kröte", "quak"],
    "🐊": ["krokodil", "crocodile", "alligator"],
    "🐢": ["schildkröte", "turtle", "langsam", "slow"],
    "🦎": ["eidechse", "lizard", "gecko"],
    "🐍": ["schlange", "snake"],
    "🐲": ["drache", "dragon"],
    "🐉": ["drache", "dragon"],
    "🦕": ["dinosaurier", "dino", "sauropod"],
    "🦖": ["dinosaurier", "dino", "t-rex", "trex"],
    "🐳": ["wal", "whale", "meer", "sea"],
    "🐋": ["wal", "whale"],
    "🐬": ["delfin", "dolphin"],
    "🦈": ["hai", "shark"],
    "🐙": ["oktopus", "octopus", "krake", "tintenfisch"],
    "🐚": ["muschel", "shell", "strand", "beach"],
    "🐌": ["schnecke", "snail", "langsam", "slow"],
    "🦋": ["schmetterling", "butterfly"],
    "🐛": ["raupe", "bug", "insekt", "wurm"],
    "🐜": ["ameise", "ant", "insekt"],
    "🐝": ["biene", "bee", "honig", "honey", "hummel"],
    "🪲": ["käfer", "beetle", "insekt"],
    "🐞": ["marienkäfer", "ladybug", "glück", "luck"],
    "🕷️": ["spinne", "spider"],
    "🕸️": ["spinnennetz", "spider web", "netz"],
    "🦂": ["skorpion", "scorpion"],
    "🦟": ["mücke", "mosquito", "stich"],
    "🌸": ["kirschblüte", "cherry blossom", "blume", "flower", "japan", "frühling", "spring"],
    "💐": ["blumenstrauß", "bouquet", "blumen", "flowers"],
    "🌷": ["tulpe", "tulip", "blume", "flower", "holland"],
    "🌹": ["rose", "blume", "flower", "liebe", "love", "romantisch"],
    "🥀": ["welk", "wilted", "traurig", "sad", "rose"],
    "🌻": ["sonnenblume", "sunflower", "sommer", "summer"],
    "🌼": ["blüte", "blossom", "blume", "flower"],
    "🌱": ["sprössling", "seedling", "pflanze", "plant", "wachsen", "grow"],
    "🪴": ["topfpflanze", "plant", "pflanze", "zimmerpflanze"],
    "🌲": ["nadelbaum", "evergreen", "tannenbaum", "tanne", "fichte", "wald", "forest"],
    "🌳": ["baum", "tree", "laubbaum", "wald"],
    "🌴": ["palme", "palm", "urlaub", "vacation", "strand", "beach", "tropen"],
    "🌵": ["kaktus", "cactus", "wüste", "desert"],
    "🌾": ["reis", "wheat", "getreide", "feld", "ernte"],
    "🍀": ["kleeblatt", "clover", "glück", "luck", "irland"],
    "🍁": ["ahornblatt", "maple", "herbst", "autumn", "kanada"],
    "🍂": ["herbst", "autumn", "laub", "fall", "blätter"],
    "🍄": ["pilz", "mushroom", "wald", "forest"],

    # Food & Drink
    "🍇": ["trauben", "grapes", "wein", "wine"],
    "🍈": ["melone", "melon"],
    "🍉": ["wassermelone", "watermelon", "sommer", "summer"],
    "🍊": ["orange", "mandarine", "tangerine", "zitrusfrucht"],
    "🍋": ["zitrone", "lemon", "sauer", "sour"],
    "🍌": ["banane", "banana"],
    "🍍": ["ananas", "pineapple"],
    "🥭": ["mango"],
    "🍎": ["apfel", "apple", "rot", "red", "obst", "fruit"],
    "🍏": ["apfel", "apple", "grün", "green", "obst", "fruit"],
    "🍐": ["birne", "pear", "obst"],
    "🍑": ["pfirsich", "peach", "hintern", "butt"],
    "🍒": ["kirschen", "cherries", "obst"],
    "🍓": ["erdbeere", "strawberry", "obst"],
    "🫐": ["blaubeeren", "blueberries", "heidelbeeren"],
    "🥝": ["kiwi", "obst"],
    "🍅": ["tomate", "tomato"],
    "🥑": ["avocado"],
    "🍆": ["aubergine", "eggplant"],
    "🥔": ["kartoffel", "potato"],
    "🥕": ["karotte", "carrot", "möhre"],
    "🌽": ["mais", "corn"],
    "🌶️": ["chili", "scharf", "hot", "pepper", "peperoni"],
    "🫑": ["paprika", "pepper", "bell pepper"],
    "🥒": ["gurke", "cucumber"],
    "🥬": ["salat", "lettuce", "grünzeug", "blatt"],
    "🥦": ["brokkoli", "broccoli"],
    "🧄": ["knoblauch", "garlic"],
    "🧅": ["zwiebel", "onion"],
    "🍞": ["brot", "bread"],
    "🥐": ["croissant", "hörnchen", "frühstück", "breakfast"],
    "🥖": ["baguette", "brot", "bread", "französisch"],
    "🥨": ["brezel", "pretzel"],
    "🥞": ["pfannkuchen", "pancakes", "frühstück"],
    "🧇": ["waffel", "waffle"],
    "🧀": ["käse", "cheese"],
    "🍖": ["fleisch", "meat", "knochen", "bone"],
    "🍗": ["hähnchen", "chicken", "keule"],
    "🥩": ["steak", "fleisch", "meat"],
    "🥓": ["speck", "bacon"],
    "🍔": ["burger", "hamburger", "fast food", "essen"],
    "🍟": ["pommes", "fries", "chips", "fast food"],
    "🍕": ["pizza"],
    "🌭": ["hotdog", "hot dog", "würstchen", "wurst"],
    "🥪": ["sandwich", "brot", "belegtes brötchen"],
    "🌮": ["taco", "mexikanisch"],
    "🌯": ["burrito", "wrap", "mexikanisch"],
    "🥙": ["döner", "kebab", "pita", "dürüm", "falafel"],
    "🧆": ["falafel"],
    "🥚": ["ei", "egg"],
    "🍳": ["spiegelei", "fried egg", "kochen", "cooking", "bratpfanne", "pfanne"],
    "🥘": ["pfanne", "eintopf", "kochen"],
    "🍲": ["eintopf", "suppe", "stew", "soup", "topf"],
    "🫕": ["fondue", "käsefondue"],
    "🥣": ["müsli", "cereal", "schüssel", "bowl", "frühstück"],
    "🥗": ["salat", "salad", "gesund", "healthy"],
    "🍿": ["popcorn", "kino", "cinema", "film", "movie"],
    "🍱": ["bento", "japanisch", "japanese"],
    "🍙": ["onigiri", "reis", "rice", "japanisch"],
    "🍚": ["reis", "rice"],
    "🍛": ["curry"],
    "🍜": ["ramen", "nudelsuppe", "nudeln", "noodles"],
    "🍝": ["spaghetti", "pasta", "nudeln", "noodles", "italienisch"],
    "🍣": ["sushi", "japanisch", "japanese"],
    "🍤": ["garnele", "shrimp", "garnelen"],
    "🥟": ["dumpling", "teigtasche", "maultasche", "dim sum"],
    "🦀": ["krabbe", "crab", "krebs"],
    "🦞": ["hummer", "lobster"],
    "🦐": ["garnele", "shrimp"],
    "🦑": ["tintenfisch", "squid", "calamari"],
    "🍦": ["eis", "ice cream", "softeis", "eiscreme"],
    "🍧": ["wassereis"],
    "🍨": ["eiscreme", "ice cream", "eis", "eiskugel"],
    "🍩": ["donut", "doughnut"],
    "🍪": ["keks", "cookie"],
    "🎂": ["geburtstagskuchen", "birthday cake", "geburtstag", "birthday", "kuchen", "cake", "torte"],
    "🍰": ["kuchen", "cake", "torte", "sahne"],
    "🧁": ["cupcake", "muffin"],
    "🥧": ["kuchen", "pie", "torte"],
    "🍫": ["schokolade", "chocolate"],
    "🍬": ["bonbon", "candy", "süßigkeit"],
    "🍭": ["lolli", "lollipop", "lutscher"],
    "🍮": ["pudding", "flan", "karamell"],
    "🍯": ["honig", "honey"],
    "🍼": ["babyflasche", "baby bottle", "milch"],
    "🥛": ["milch", "milk", "glas"],
    "☕": ["kaffee", "coffee", "tasse", "cup", "tee", "tea", "heiß", "hot"],
    "🫖": ["teekanne", "teapot", "tee", "tea"],
    "🍵": ["tee", "tea", "matcha", "grüner tee"],
    "🍶": ["sake", "japanisch"],
    "🍾": ["sekt", "champagner", "champagne", "feiern", "party", "prost"],
    "🍷": ["wein", "wine", "rotwein"],
    "🍸": ["cocktail", "martini"],
    "🍹": ["cocktail", "tropical", "drink", "urlaub"],
    "🍺": ["bier", "beer", "prost", "krug"],
    "🍻": ["bier", "beer", "prost", "anstoßen", "cheers"],
    "🥂": ["anstoßen", "cheers", "sekt", "champagner", "prost"],
    "🥃": ["whisky", "whiskey", "schnaps", "bourbon"],
    "🥤": ["getränk", "drink", "cola", "limo", "strohhalm"],
    "🧋": ["bubble tea", "boba"],
    "🧃": ["saft", "juice", "capri sun", "trinkpäckchen"],
    "🧊": ["eis", "ice", "eiswürfel"],
    "🍴": ["besteck", "essen", "eat", "gabel", "messer", "fork", "knife", "restaurant"],
    "🍽️": ["essen", "eat", "restaurant", "teller", "plate", "besteck"],
    "🥄": ["löffel", "spoon"],
    "🔪": ["messer", "knife", "kochen"],
    "🥢": ["stäbchen", "chopsticks", "asiatisch"],

    # Travel & Places
    "🌍": ["welt", "world", "erde", "earth", "europa", "europe", "afrika", "africa", "globus"],
    "🌎": ["welt", "world", "erde", "earth", "amerika", "america", "globus"],
    "🌏": ["welt", "world", "erde", "earth", "asien", "asia", "globus"],
    "🗺️": ["weltkarte", "world map", "karte", "map"],
    "🏔️": ["berg", "mountain", "schnee", "snow", "alpen"],
    "⛰️": ["berg", "mountain"],
    "🌋": ["vulkan", "volcano"],
    "🏕️": ["camping", "zelt", "tent", "natur", "wald"],
    "🏖️": ["strand", "beach", "urlaub", "vacation", "meer", "sea", "sonne"],
    "🏜️": ["wüste", "desert"],
    "🏝️": ["insel", "island"],
    "🏗️": ["baustelle", "construction", "kran", "crane", "bauen"],
    "🏠": ["haus", "house", "home", "zuhause"],
    "🏡": ["haus", "house", "home", "garten", "garden"],
    "🏢": ["büro", "office", "gebäude", "building", "firma", "company"],
    "🏥": ["krankenhaus", "hospital", "arzt", "doctor"],
    "🏦": ["bank"],
    "🏨": ["hotel", "übernachtung"],
    "🏪": ["laden", "shop", "store", "einkaufen"],
    "🏫": ["schule", "school", "bildung", "education"],
    "🏭": ["fabrik", "factory", "industrie"],
    "🏰": ["schloss", "castle", "burg"],
    "🏯": ["schloss", "castle", "japanisch", "burg"],
    "💒": ["hochzeit", "wedding", "kirche"],
    "⛪": ["kirche", "church"],
    "🕌": ["moschee", "mosque"],
    "⛲": ["brunnen", "fountain"],
    "🌃": ["nacht", "night", "stadt", "city", "sterne"],
    "🏙️": ["stadt", "city", "skyline"],
    "🌅": ["sonnenaufgang", "sunrise", "sonne", "morgen", "morning"],
    "🌆": ["dämmerung", "dusk", "stadt", "abend"],
    "🌇": ["sonnenuntergang", "sunset", "abend"],
    "🌉": ["brücke", "bridge", "nacht"],
    "🎡": ["riesenrad", "ferris wheel", "jahrmarkt", "kirmes"],
    "🎢": ["achterbahn", "roller coaster", "jahrmarkt", "kirmes"],
    "🚂": ["lok", "lokomotive", "locomotive", "zug", "train", "dampflok"],
    "🚃": ["zug", "train", "wagon", "waggon", "bahn"],
    "🚄": ["zug", "train", "schnellzug", "ice", "tgv", "highspeed"],
    "🚅": ["zug", "train", "shinkansen", "schnellzug"],
    "🚆": ["zug", "train", "bahn"],
    "🚇": ["ubahn", "metro", "underground"],
    "🚈": ["sbahn", "light rail"],
    "🚉": ["bahnhof", "station", "zug", "train"],
    "🚌": ["bus", "reisebus"],
    "🚍": ["bus"],
    "🚑": ["krankenwagen", "ambulance", "rettungswagen", "notfall"],
    "🚒": ["feuerwehr", "fire engine", "feuerwehrauto"],
    "🚓": ["polizei", "police car", "polizeiauto"],
    "🚕": ["taxi", "cab"],
    "🚗": ["auto", "car", "automobile", "pkw", "wagen", "fahrzeug", "vehicle"],
    "🚘": ["auto", "car", "pkw"],
    "🚙": ["suv", "auto", "car", "geländewagen", "jeep"],
    "🛻": ["pickup", "truck", "transporter"],
    "🚚": ["lieferwagen", "delivery", "lkw", "truck", "umzug"],
    "🚛": ["lkw", "truck", "sattelzug", "brummi"],
    "🚜": ["traktor", "tractor", "bauer", "farmer", "landwirtschaft"],
    "🏎️": ["rennwagen", "racing", "formel 1", "f1", "rennauto", "schnell"],
    "🏍️": ["motorrad", "motorcycle", "bike"],
    "🛵": ["roller", "scooter", "moped", "vespa"],
    "🚲": ["fahrrad", "bicycle", "bike", "rad", "radfahren"],
    "🛴": ["roller", "scooter", "kickscooter", "tretroller"],
    "🚏": ["bushaltestelle", "bus stop", "haltestelle"],
    "⛽": ["tankstelle", "gas station", "benzin", "tanken", "sprit"],
    "🚨": ["polizei", "police", "blaulicht", "sirene", "alarm", "notfall"],
    "🚥": ["ampel", "traffic light"],
    "🚦": ["ampel", "traffic light"],
    "🚧": ["baustelle", "construction", "achtung"],
    "⚓": ["anker", "anchor", "schiff", "ship", "hafen"],
    "⛵": ["segelboot", "sailboat", "segeln", "sailing"],
    "🚤": ["speedboot", "speedboat", "boot", "boat", "schnell"],
    "🛳️": ["kreuzfahrt", "cruise", "schiff", "ship"],
    "🚢": ["schiff", "ship", "fähre"],
    "✈️": ["flugzeug", "airplane", "plane", "fliegen", "fly", "reise", "travel"],
    "🛩️": ["flugzeug", "airplane", "klein"],
    "🛫": ["abflug", "departure", "flugzeug", "fliegen"],
    "🛬": ["ankunft", "arrival", "flugzeug", "landen"],
    "🪂": ["fallschirm", "parachute"],
    "🚁": ["hubschrauber", "helicopter", "heli"],
    "🚀": ["rakete", "rocket", "weltraum", "space", "start", "launch"],
    "🛸": ["ufo", "alien", "fliegende untertasse"],
    "🌈": ["regenbogen", "rainbow", "bunt", "colorful"],
    "🔥": ["feuer", "fire", "flamme", "heiß", "hot", "lit", "geil", "krass"],
    "💧": ["tropfen", "drop", "wasser", "water"],
    "🌊": ["welle", "wave", "meer", "sea", "ozean", "ocean", "surfen"],
    "❄️": ["schneeflocke", "snowflake", "winter", "kalt", "cold"],
    "⛄": ["schneemann", "snowman", "winter", "schnee", "snow"],
    "☀️": ["sonne", "sun", "sommer", "summer", "warm", "schön"],
    "🌙": ["mond", "moon", "nacht", "night", "halbmond"],
    "⭐": ["stern", "star", "favorit"],
    "🌟": ["stern", "star", "glitzer", "funkeln"],
    "⚡": ["blitz", "lightning", "strom", "electricity", "energie", "schnell"],
    "☔": ["regen", "rain", "regenschirm", "umbrella", "nass"],
    "🌪️": ["tornado", "wirbelsturm", "sturm"],

    # Activities
    "🎃": ["halloween", "kürbis", "pumpkin"],
    "🎄": ["weihnachten", "christmas", "weihnachtsbaum", "tannenbaum"],
    "✨": ["funkeln", "sparkle", "glitzer", "magic", "neu", "new", "sterne"],
    "🎈": ["ballon", "balloon", "party", "geburtstag", "birthday"],
    "🎉": ["party", "feier", "geburtstag", "gratulation", "congratulations", "yay"],
    "🎊": ["konfetti", "confetti", "party", "feier"],
    "🎁": ["geschenk", "gift", "present", "geburtstag", "weihnachten"],
    "🏆": ["pokal", "trophy", "gewinner", "winner", "sieg", "champion"],
    "🏅": ["medaille", "medal", "gewinner", "sport"],
    "🥇": ["gold", "erster", "first", "gewinner", "medaille"],
    "🥈": ["silber", "silver", "zweiter", "second", "medaille"],
    "🥉": ["bronze", "dritter", "third", "medaille"],
    "⚽": ["fußball", "football", "soccer", "ball", "sport"],
    "⚾": ["baseball", "sport", "ball"],
    "🏀": ["basketball", "sport", "ball"],
    "🏐": ["volleyball", "sport", "ball"],
    "🏈": ["american football", "sport", "ball", "nfl"],
    "🎾": ["tennis", "sport", "ball", "schläger"],
    "🏓": ["tischtennis", "ping pong", "sport"],
    "🏸": ["badminton", "federball", "sport"],
    "🥊": ["boxen", "boxing", "handschuh", "sport", "kampf"],
    "🥋": ["kampfsport", "martial arts", "karate", "judo"],
    "⛳": ["golf", "sport"],
    "🎣": ["angeln", "fishing", "fisch"],
    "🎿": ["ski", "skiing", "winter", "sport", "schnee"],
    "🛷": ["schlitten", "sled", "winter", "schnee"],
    "🎯": ["ziel", "target", "treffer", "bullseye", "dart", "darts"],
    "🎮": ["videospiel", "gaming", "controller", "zocken", "spielen", "game", "konsole"],
    "🕹️": ["joystick", "gaming", "arcade", "spielen"],
    "🎰": ["spielautomat", "slot machine", "casino", "glücksspiel"],
    "🎲": ["würfel", "dice", "spiel", "game", "zufall"],
    "🧩": ["puzzle", "rätsel"],
    "🧸": ["teddy", "teddybär", "kuscheltier", "plüsch"],
    "🪩": ["discokugel", "disco", "party", "mirror ball", "tanzen"],
    "♟️": ["schach", "chess", "bauer", "pawn"],
    "🎭": ["theater", "maske", "drama", "comedy"],
    "🎨": ["kunst", "art", "malen", "paint", "palette", "künstler"],
    "🧵": ["faden", "thread", "nähen", "sewing"],
    "🧶": ["wolle", "yarn", "stricken", "knitting"],
    "🎵": ["musik", "music", "note"],
    "🎶": ["musik", "music", "noten", "notes"],
    "🎤": ["mikrofon", "microphone", "singen", "sing", "karaoke"],
    "🎧": ["kopfhörer", "headphones", "musik", "music"],
    "📻": ["radio"],
    "🎷": ["saxophon", "saxophone", "jazz", "musik"],
    "🎸": ["gitarre", "guitar", "rock", "musik"],
    "🎹": ["klavier", "piano", "keyboard", "musik"],
    "🎺": ["trompete", "trumpet", "musik"],
    "🎻": ["geige", "violin", "musik"],
    "🥁": ["trommel", "drum", "schlagzeug", "musik"],

    # Objects
    "👓": ["brille", "glasses"],
    "🕶️": ["sonnenbrille", "sunglasses", "cool"],
    "👔": ["krawatte", "tie", "business", "arbeit", "formal"],
    "👕": ["tshirt", "t-shirt", "shirt", "oberteil"],
    "👖": ["jeans", "hose", "pants"],
    "👗": ["kleid", "dress"],
    "👘": ["kimono", "japanisch"],
    "👙": ["bikini", "strand", "beach", "sommer"],
    "👟": ["schuhe", "sneaker", "turnschuh", "sport"],
    "👞": ["schuhe", "shoes", "herrenschuh"],
    "👠": ["high heels", "absatzschuhe", "schuh"],
    "👑": ["krone", "crown", "könig", "king", "königin", "queen"],
    "🎩": ["zylinder", "top hat", "gentleman", "hut"],
    "🎓": ["abschluss", "graduation", "uni", "studium", "doktorhut"],
    "🧢": ["kappe", "cap", "mütze", "basecap"],
    "💍": ["ring", "verlobung", "engagement", "hochzeit", "wedding", "diamant"],
    "💎": ["diamant", "diamond", "edelstein", "gem", "juwel"],
    "📱": ["handy", "smartphone", "phone", "telefon", "mobile"],
    "📲": ["handy", "phone", "download"],
    "☎️": ["telefon", "telephone", "phone", "anrufen"],
    "💻": ["laptop", "computer", "notebook", "pc"],
    "🖥️": ["computer", "desktop", "pc", "bildschirm", "monitor"],
    "🖨️": ["drucker", "printer"],
    "⌨️": ["tastatur", "keyboard"],
    "🖱️": ["maus", "mouse", "computer"],
    "💽": ["cd", "disk", "speicher"],
    "💾": ["diskette", "floppy", "speichern", "save"],
    "💿": ["cd", "dvd", "disk"],
    "📀": ["dvd", "cd", "film"],
    "🎥": ["kamera", "camera", "film", "movie"],
    "📷": ["kamera", "camera", "foto", "photo"],
    "📸": ["kamera", "camera", "foto", "photo", "blitz", "flash"],
    "📹": ["videokamera", "video camera", "film"],
    "📺": ["fernseher", "tv", "television", "fernsehen"],
    "🔍": ["suchen", "search", "lupe", "magnifying glass"],
    "🔎": ["suchen", "search", "lupe"],
    "💡": ["glühbirne", "light bulb", "idee", "idea", "licht", "light"],
    "🔦": ["taschenlampe", "flashlight", "licht"],
    "📖": ["buch", "book", "lesen", "read"],
    "📕": ["buch", "book"],
    "📗": ["buch", "book"],
    "📘": ["buch", "book"],
    "📚": ["bücher", "books", "lesen", "read", "bibliothek", "library"],
    "📝": ["notiz", "memo", "schreiben", "write", "note"],
    "📄": ["dokument", "document", "seite", "page", "datei", "file"],
    "📰": ["zeitung", "newspaper", "nachrichten", "news"],
    "💰": ["geld", "money", "beutel", "bag", "reich"],
    "💴": ["geld", "yen", "japanisch"],
    "💵": ["geld", "dollar", "schein", "bill"],
    "💶": ["geld", "euro", "schein"],
    "💷": ["geld", "pfund", "pound"],
    "💸": ["geld", "money", "weg", "ausgeben", "spend", "teuer"],
    "💳": ["kreditkarte", "credit card", "karte", "bezahlen", "pay"],
    "✉️": ["brief", "letter", "email", "mail", "post"],
    "📧": ["email", "e-mail", "mail", "nachricht"],
    "📦": ["paket", "package", "box", "lieferung", "delivery"],
    "📫": ["briefkasten", "mailbox", "post"],
    "📮": ["briefkasten", "postbox", "post"],
    "✏️": ["bleistift", "pencil", "schreiben"],
    "🖊️": ["kugelschreiber", "pen", "stift", "schreiben"],
    "🖌️": ["pinsel", "paintbrush", "malen", "kunst"],
    "📅": ["kalender", "calendar", "termin", "datum", "date"],
    "📆": ["kalender", "calendar"],
    "📋": ["klemmbrett", "clipboard", "liste", "list"],
    "📌": ["pinnnadel", "pushpin", "pin", "merken"],
    "📎": ["büroklammer", "paperclip", "klammer"],
    "✂️": ["schere", "scissors", "schneiden", "cut"],
    "🔒": ["schloss", "lock", "sicher", "secure", "gesperrt"],
    "🔓": ["offen", "unlock", "open", "entsperrt"],
    "🔑": ["schlüssel", "key"],
    "🗝️": ["schlüssel", "key", "alt", "old"],
    "🔨": ["hammer", "werkzeug", "tool", "bauen"],
    "🪓": ["axt", "axe", "holz", "wood"],
    "🔧": ["schraubenschlüssel", "wrench", "werkzeug", "tool", "reparieren"],
    "🪛": ["schraubenzieher", "screwdriver", "werkzeug"],
    "🔩": ["schraube", "screw", "mutter", "bolt"],
    "⚙️": ["zahnrad", "gear", "einstellungen", "settings", "mechanik"],
    "🧰": ["werkzeugkasten", "toolbox", "werkzeug"],
    "🧲": ["magnet"],
    "🪜": ["leiter", "ladder"],
    "🧪": ["reagenzglas", "test tube", "labor", "chemie", "science"],
    "🧬": ["dna", "genetik", "gen", "biologie"],
    "🔬": ["mikroskop", "microscope", "labor", "science"],
    "🔭": ["teleskop", "telescope", "sterne", "astronomie"],
    "💉": ["spritze", "syringe", "impfung", "vaccine", "arzt", "nadel"],
    "💊": ["pille", "pill", "tablette", "medizin", "medicine", "arzt"],
    "🩹": ["pflaster", "bandaid", "band-aid", "wunde"],
    "🩺": ["stethoskop", "stethoscope", "arzt", "doctor"],
    "🚪": ["tür", "door", "eingang", "ausgang"],
    "🪞": ["spiegel", "mirror"],
    "🪟": ["fenster", "window"],
    "🛏️": ["bett", "bed", "schlafen", "sleep"],
    "🛋️": ["sofa", "couch", "wohnzimmer"],
    "🪑": ["stuhl", "chair", "sitzen"],
    "🚽": ["toilette", "toilet", "klo", "wc"],
    "🚿": ["dusche", "shower", "duschen", "bad"],
    "🛁": ["badewanne", "bathtub", "bad", "baden"],
    "🧹": ["besen", "broom", "kehren", "putzen"],
    "🧺": ["korb", "basket", "wäsche", "laundry"],
    "🧻": ["klopapier", "toilet paper", "toilettenpapier"],
    "🧼": ["seife", "soap", "waschen"],
    "🪥": ["zahnbürste", "toothbrush", "zähne"],
    "🧽": ["schwamm", "sponge", "putzen"],
    "🧯": ["feuerlöscher", "fire extinguisher"],
    "🛒": ["einkaufswagen", "shopping cart", "einkaufen", "supermarkt"],

    # Symbols
    "⚠️": ["warnung", "warning", "achtung", "vorsicht", "caution"],
    "⛔": ["verboten", "stop", "no entry", "halt"],
    "🚫": ["verboten", "prohibited", "nein", "no", "stop"],
    "✅": ["fertig", "done", "check", "erledigt", "ok", "ja", "yes", "richtig", "correct", "häkchen"],
    "❌": ["falsch", "wrong", "nein", "no", "fehler", "error", "kreuz", "cross"],
    "❓": ["frage", "question"],
    "❗": ["achtung", "wichtig", "important", "ausrufezeichen"],
    "♻️": ["recycling", "umwelt", "grün"],
    "➡️": ["rechts", "right", "pfeil", "arrow", "weiter", "next"],
    "⬅️": ["links", "left", "pfeil", "arrow", "zurück", "back"],
    "⬆️": ["oben", "up", "pfeil", "arrow", "hoch"],
    "⬇️": ["unten", "down", "pfeil", "arrow", "runter"],
    "🔴": ["rot", "red", "kreis", "circle"],
    "🟠": ["orange", "kreis", "circle"],
    "🟡": ["gelb", "yellow", "kreis", "circle"],
    "🟢": ["grün", "green", "kreis", "circle"],
    "🔵": ["blau", "blue", "kreis", "circle"],
    "🟣": ["lila", "purple", "violett", "kreis", "circle"],
    "⚫": ["schwarz", "black", "kreis", "circle"],
    "⚪": ["weiß", "white", "kreis", "circle"],
    "©️": ["copyright"],
    "®️": ["registered", "marke"],
    "™️": ["trademark", "marke"],

    # Flags — deutsche Bezeichnungen
    "🇩🇪": ["deutschland", "germany", "deutsch", "german", "brd"],
    "🇦🇹": ["österreich", "austria"],
    "🇨🇭": ["schweiz", "switzerland"],
    "🇺🇸": ["usa", "amerika", "america", "vereinigte staaten"],
    "🇬🇧": ["england", "großbritannien", "uk", "vereinigtes königreich", "british"],
    "🇫🇷": ["frankreich", "france", "französisch"],
    "🇮🇹": ["italien", "italy"],
    "🇪🇸": ["spanien", "spain"],
    "🇵🇹": ["portugal"],
    "🇳🇱": ["niederlande", "netherlands", "holland"],
    "🇧🇪": ["belgien", "belgium"],
    "🇩🇰": ["dänemark", "denmark"],
    "🇸🇪": ["schweden", "sweden"],
    "🇳🇴": ["norwegen", "norway"],
    "🇫🇮": ["finnland", "finland"],
    "🇮🇪": ["irland", "ireland"],
    "🇵🇱": ["polen", "poland"],
    "🇨🇿": ["tschechien", "czechia", "czech"],
    "🇭🇺": ["ungarn", "hungary"],
    "🇷🇴": ["rumänien", "romania"],
    "🇭🇷": ["kroatien", "croatia"],
    "🇬🇷": ["griechenland", "greece"],
    "🇹🇷": ["türkei", "turkey"],
    "🇷🇺": ["russland", "russia"],
    "🇺🇦": ["ukraine"],
    "🇯🇵": ["japan", "japanisch"],
    "🇨🇳": ["china", "chinesisch"],
    "🇰🇷": ["südkorea", "south korea", "korea"],
    "🇮🇳": ["indien", "india"],
    "🇧🇷": ["brasilien", "brazil"],
    "🇲🇽": ["mexiko", "mexico"],
    "🇨🇦": ["kanada", "canada"],
    "🇦🇺": ["australien", "australia"],
    "🇪🇺": ["eu", "europa", "europe", "europäische union"],
}
